### ISSUE TITLE
Material replacer for body parts is not networked properly

### ISSUE THREAD

**Issue by Em3rgencyLT** [RE-SS3D/SS3D#100]
### Expected Behavior
Detached limbs should be of the same color as the body they came from, for all players.

### Current Behavior
The host sees the colors correctly, the clients do not.

### Steps to Reproduce
1. Host a game
2. Connect to the game with another client
3. Target a body part and hit F until it falls off
4. Observe the differences on the host and on the client

**Comment by Dyhr** [comment]
@Em3rgencyLT, can you screenshot the difference for clarity?
