### ISSUE TITLE
Add tests for container system

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#1024]
## Summary

We need to implement series of test for the container system. This is work in progress as we must define which test do we want to see implemented.

## Dependencies

Issue #984 
Maybe Issue #969 (need discussion)

**Comment by Ryan089** [comment]
This is likely to be wasted work if completed before #969 is done, because it is likely that only a few test cases will survive a significant refactor like that.

**Comment by stilnat** [comment]
The task you mentioned still need discussion as this may not be the way we want to go. 
You're right to mention it though, because the system does need change. 
Since we talked about the humble object pattern, I think this is probably the way we should go, but I need to discuss about it with john. 
In any case, I don't think it would be wasted work, as most methods would be preserved, or at least what they're supposed to do. The tests could need some minor changes to adapt to this refactor, but I'm confident that it won't be too hard to adapt them.

**Comment by stilnat** [comment]
enough container tests for now
