### ISSUE TITLE
Lighting Setup

### ISSUE THREAD

**Issue by Dyhr** [RE-SS3D/SS3D#104]
**Description**
The lighting needs to be set up as intended. You can find some reference videos on our previous incarnation's Patreon https://www.patreon.com/ss3d.

**Requirements:**
- Use deferred rendering to support as many lights as we want.
- There should be no ambient lighting.
- All lighting should come from lamps. If there are no lamps, it should be pitch black.
- Only static structures like walls will cast shadows

**_Not_ Requirements:**
- Fog of war / field of view / whatever you want to call not being able to see through walls is **_not_** within the scope of this issue
- Fake shadows under players and objects are **_not_** within the scope of this issue
- Implementing half lambert lighting as seen in the references **_not_** within the scope of this issue

**Comment by Markus-P-L** [comment]
I made a PR for this issue. You may assign me.
