### ISSUE TITLE
Putting items on the ground sometimes make them glitch.

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#1043]
## Summary

Sometimes after putting items on the ground, they get inside the ground and glitch.

## Steps to Reproduce

- Open tile creator menu by pressing B.
- Spawn a bikehorn.
- grab the bikehorn and put it elsewhere on the ground.
- Repeat step 3 until you notice it glitching.

## Context

related to PR #995 , I don't remember this bug happening before.

**Comment by henkhooft** [comment]
Likely due to the different spawn position via the TileMapCreator, which is the mouse position with y = 0

**Comment by stilnat** [comment]
So it should be an easy fix then. Yeah the items seem to spawn "inside" the tile, a bit too low.

**Comment by stilnat** [comment]
seems fixed
