### ISSUE TITLE
Blob Shadows

### ISSUE THREAD

**Issue by Dyhr** [RE-SS3D/SS3D#105]
Moving objects will now have shadows from lights. To make things still look good, they should have blob shadows, ie. a fake small transparent blob underneath them.
This is typically implemented with a projector in Unity.
Optional features include:
- Fading away the "shadow" when you are far above the floor
- Having a different shape for different objects, while keeping it looking good

**Comment by Markus-P-L** [comment]
Commenting so I can be assigned.
