### ISSUE TITLE
Faster Tilemap Construction

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#1056]
## Summary

Implement a couple features into the tilemap construction system to speed up the process of mapping.

## Goal 

Currently you can only place 1 tile at a time. Meaning you will need to click 100 times to build a floor that is 10x10. This is not time efficient. Add two functionalities to the tilemap system to speed this up:

1. Ability to click (hold) and drag, placing an object on every tile you drag your mouse while being held. 

2. Ability to hold shift while click (hold) and drag, creating a rectangle of prefabs to place.

(These of course should respect normal tilemap construction rules like not being able to build where something is, etc.)

**Comment by iamteapot422** [comment]
assign me
