### ISSUE TITLE
Can't delete items that are containers

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#1077]
## Summary

Cant delete items from the tilemap that are containers. Something with the containers scripts is preventing it.

(It may actually be the animator script but the container script... not sure)

## Current Behavior

When you try to delete a toolbox (or other item that is also a container), it just goes into the player's hand, it doesn't get removed.

## Steps to Reproduce

- Place a toolbox on the tilemap, then try to delete it.

## Context

https://user-images.githubusercontent.com/41941008/222939697-ac33eff7-bb94-4326-a4b5-7988dffe23c1.mp4

**Comment by iamteapot422** [comment]
Works fine for all items, except of toolbox. Items dont go into player's hand after input system prs

**Comment by stilnat** [comment]
Bug confirmed for toolboxes only.

**Comment by cosmiccoincidence** [comment]
After some additional testing it appears that it's an issue with the container components. I used a backpack for test (which I could delete from the tilemap) and added the container components similar to how its set up on the toolbox and I can no longer delete the backpack.

**Comment by cosmiccoincidence** [comment]
It's possible it could actually be the animator component, not the container component. I am unable to delete the EngiBorg from the tilemap either I realized, and I do not see a container script anywhere on it.
