### ISSUE TITLE
"Port already in use" bug in editor

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#1079]
## Summary

There's a recurring issue with the port being already in use when play testing in editor. That need a fix.
Only current way to get rid of it is either to change the port or close and open unity again.

## Steps to Reproduce

- Launch the game as host in editor
- Play around
- Stop the game by pressing the play button
- Try to press play again
- See the error message "Port already in use"

The bug is unreliable and is sometime hard to reproduce

**Comment by cosmiccoincidence** [comment]
Seteron's fix didn't resolve the issue.

**Comment by iamteapot422** [comment]
Making the project folder an exception for antivirus and windows defender works

**Comment by stilnat** [comment]
interesting, we need to test that and close the issue if it works

**Comment by stilnat** [comment]
Does someone experiment the bug still ? I didn't since I followed the suggestion of iamteapot.

**Comment by cosmiccoincidence** [comment]
> Does someone experiment the bug still ? I didn't since I followed the suggestion of iamteapot.

Comment a link to your commit that you think fixed it so someone can test it.

**Comment by cosmiccoincidence** [comment]
@stilnat see my previous comment.

**Comment by cosmiccoincidence** [comment]
@stilnat Are you experiencing the issuing still? I haven't seen the issue on my side in a while.
If the issue can be fixed via making an exception for antivirus + firewall, I suggest we comment that on the gitbook somewhere and close this issue.

**Comment by stilnat** [comment]
@cosmiccoincidence no it's been a long while too, I think we can consider it solved by @iamteapot422 . 20 bucks for him.
