### ISSUE TITLE
Tilemap construction doesn't prevent non-tilemap interaction PART 2

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#1090]
## Summary

The tilemap construction window doesn't prevent interaction with the rest of the world. Part 2.

## Current Behavior

<kbd>Shift</kbd> is used to toggle walking/running. It is also used by the tilemap editor for replacing tiles (hold <kbd>Shift</kbd> and click <kbd>LMB</kbd>).

The issue is, that when you are building a map and using the replace feature, you end up also changing your walk/run toggle repeatedly which becomes annoying while building a map.

## Steps to Reproduce

- Open the tilemap window and select a floor tile
- Move back and forth to confirm your current walk/run state
- Hold <kbd>Shift</kbd> and click <kbd>LMB</kbd> to replace a few floor tiles
- Move back and forth to confirm your walk/run state has changed

## Expected Behavior

Non-tilemap interactions should be ignored in favor of tilemap interactions while the tilemap editor is open.

## Context

Related issues
#966 
#1086
#1091 

## Media

https://user-images.githubusercontent.com/41941008/223557693-166ae765-47c3-4b88-8c73-1c509952565b.mp4

**Comment by stilnat** [comment]
I tried really hard to break this with no success, code is legit and it solves what it says it solves. Great work !
