### ISSUE TITLE
Inventory bugs

### ISSUE THREAD

**Issue by joaoburatto** [RE-SS3D/SS3D#111]
When you open a locker, you can't close it.
Putting items on the pockets gives you a null reference error.
![image](https://user-images.githubusercontent.com/46575243/72684160-ef396480-3abc-11ea-87de-cc57202dcfcc.png)
This button doesn't do anything.
![image](https://user-images.githubusercontent.com/46575243/72684132-a7b2d880-3abc-11ea-9f39-4db8b104f075.png)

**Comment by Em3rgencyLT** [comment]
Should be 3 separate issues

**Comment by joaoburatto** [comment]
> Should be 3 separate issues
I won't create 3 issues just for that

**Comment by Em3rgencyLT** [comment]
These are 3 completely unrelated issues. It doesn't matter that they are small. Someone solving any 1 of these will have to be looking in different areas. Additionally they can be solved by 3 people at the same time, each taking 1 issue.

Should be 3 issues.

**Comment by Dyhr** [comment]
Closing, to be reopened as 3 issues
