### ISSUE TITLE
Cannot close lockers

### ISSUE THREAD

**Issue by Dyhr** [RE-SS3D/SS3D#113]
When you open a locker, you can't close it.

### Expected Behavior
You can close the locker after opening it

### Current Behavior
When you open a locker, you can't close it.

### Steps to Reproduce

1. Open a locker
2. Attempt to close it

**Comment by Puddleduckable** [comment]
by opening it, i assume you mean flinging an object at the locker to open it up, i dont think there is a button to open it. if you change the rigidbody's angular drag of the locker door to 2, you should be able to just push it closed.

very first time i did anything git, sorry.

**Comment by Dyhr** [comment]
This is just a transcript of @joaoburatto 's report. He provided fewer details than this.

**Comment by cosmiccoincidence** [comment]
Closing this since it's so similar to #161, both can be handled in the same issue.
