### ISSUE TITLE
Putting items on the pockets throws a NullReferenceException

### ISSUE THREAD

**Issue by Dyhr** [RE-SS3D/SS3D#114]
Putting items on the pockets throws a NullReferenceException

### Expected Behavior
No exceptions are thrown

### Current Behavior
Putting items on the pockets throws a NullReferenceException

### Steps to Reproduce
1. Put items on the pockets

**Comment by r-oylo** [comment]
I would like to work on this issue if that's OK with you ! Could someone assign me to it ? Thanks!

**Comment by Dyhr** [comment]
No problem. If it's just small bugs like this, you don't need to be assigned, you can just do it make PR
