### ISSUE TITLE
[Task] Add basic rounds

### ISSUE THREAD

**Issue by Em3rgencyLT** [RE-SS3D/SS3D#118]
**Description**
Gameplay in SS13 is inherently round based. A lot of mechanics flows from that. Having a basic round framework in place, opens up the doors for a lot of other features to begin implementation.

**User stories**
As the server, I should be able to see the current remaining round time
As the client, I should be able to see the current remaining round time
As the server, I should reset the game world when round time reaches 0
As the server, I should be able to restart the round at any time

**Comment by cosmiccoincidence** [comment]
Closed by #141
