### ISSUE TITLE
Fix log type display

### ISSUE THREAD

**Issue by joaoburatto** [RE-SS3D/SS3D#1180]
## Summary

Currently the logs displays `typeof(PlayerSystem)`, which results in:
`SS3D.Systems.PlayerControl.PlayerSystem`
The correct would be `nameof(PlayerSystem)`, which results in:
`PlayerSystem`

![image](https://user-images.githubusercontent.com/46575243/232947454-97c448aa-770d-4078-bcb7-5a788d4df7f7.png)

## Goal 

Make the logs cleaner.

**Comment by stilnat** [comment]
Changing that to medium difficulty, did not try that much but I did a bit and Serilog being in the mix makes that not trivial.
