### ISSUE TITLE
Finish exporting the health design doc to gitbook

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#1187]
## Summary

Take what's missing in this doc https://docs.google.com/document/d/1DnpwresKmUe3hDzDFpGI7o2iU4xUKfkx6gVieuP5pVM/edit#heading=h.apft046zl2hw)
and put it on gitbook, in the design section.
Notice the stuff missing, like the doc on the circulatory system.

**Comment by cosmiccoincidence** [comment]
The whole doc is ported over already afaik.

Circulatory is located at: https://ss3d.gitbook.io/design/entities/health/body-systems
