### ISSUE TITLE
Host outside of editor getting kicked when client connects

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#1193]
## Summary

Everything in the title, this makes testing the client in editor impossible and will very likely be a strong issue in the near future.

## Steps to Reproduce

- Build the game
- Launch the build with host
- embark with host
- connect with client
- See how the host is immediately kicked out.

## Possible Solution

It seems that it's linked to the fishnet modification, removing it seems to solve the issue.
https://github.com/RE-SS3D/SS3D/pull/1140/files#diff-3c3e93b3d33d5c572cb20f3789ccf70708ae7699544120323c0baacd02ad1259

Issue is, half our editor tests are depending on it. Fishnet should have implemented a way to disable network attributes so we can remove this modification without breaking our tests. See this conversation : 

https://github.com/FirstGearGames/FishNet/pull/317

Upgrading fishnet and removing the modified code should then solve the issue.

**Comment by Ryan089** [comment]
Did Fishnet actually resolve this, or did they simply introduce an "official" way of doing what we are already doing (i.e. the thing that gave us the bug)? It seemed pretty clear from the Fishnet developer that the changes would lead to undesirable behaviour.

**Comment by stilnat** [comment]
official way. details in the conversation linked above.

**Comment by Ryan089** [comment]
In that case, simply reverting our changes and updating Fishnet would not help.
