### ISSUE TITLE
Map is Broken

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#1204]
## Summary

The map is broken/missing.

## Steps to Reproduce

Launch the game. 

## Context

Likely caused by #1185

**Comment by stilnat** [comment]
Should work when pressing Lobby scene instead of Startup scene : 
![image](https://github.com/RE-SS3D/SS3D/assets/14344825/647154f4-956d-45d7-9002-e11a760dae53)

If you could confirm that, we could maybe change the content of this issue.
