### ISSUE TITLE
Update docs & issue templates

### ISSUE THREAD

**Issue by TimFinucane** [RE-SS3D/SS3D#121]
Issue templates should be reduced to just bug, bug and general task, or bug, general task, and suggestion.

- Update readme to remove references to defunct "develop" branch
- For more in-depth contributing info (including model style guide), people should be referred to website, which is preferred place for up to date contrib info and modelling info.

Any other needed updates to these docs can be commented below.

**Comment by cosmiccoincidence** [comment]
There are more references to the develop branch in Contributing.md in the PR section.
