### ISSUE TITLE
Add search bar to tilemap construction menu

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#1223]
## Summary

The current tilemap construction menu lacks a search bar  (accessed by pressing B), add one at the top to quickly find stuff in it.
The search doesn't need to be case sensitive.

**Comment by cosmiccoincidence** [comment]
A research bar? I think you mean a search bar.

**Comment by stilnat** [comment]
> A research bar? I think you mean a search bar.

hehe yes
