### ISSUE TITLE
PDA on ground when client late joins

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#1232]
## Summary
When client late joins, somehow the position of the PDA on host does not get updated, see the picture below.

![image](https://github.com/RE-SS3D/SS3D/assets/14344825/8f66e8cd-b028-41ec-9ced-dda6a5039b6c)

## Steps to Reproduce

- host a game
- late join with client
- look at the difference between host and client in terms of PDA position

## Solution

Solution should be more than a simple band aid, it should work for other items displayed in container as well. We currently don't have much container displaying their content in game but you can create one for tests.

**Comment by Sjerty** [comment]
Heya, decided to look into it, just because it's seemed interesting and found out that other people encountered simillar problem, we even get simillar warnings in logs:
https://github.com/FirstGearGames/FishNet/issues/435

So the issue was fixed in 3.11.2R, while we have 3.10.7R.
https://github.com/FirstGearGames/FishNet/releases/tag/3.11.2

May I suggest updating FishNet to that version and look at our issue from there? I can try updating it myself in my branch, but is there something I should know before updating, maybe some advice? C:

**Comment by stilnat** [comment]
@Sjerty interesting take, well might well be that, but we won't know without trying. I updated twice fishnet on this project, I don't fully remember all steps but should be somewhat straightforward. Only thing I can say is that you should delete the current fishnet folder before updating.

You can give it a try and we'll see how it goes.

**Comment by Sjerty** [comment]
@stilnat Updated FishNet without any problems, warnings I've talked about is gone, but I did encounter some problem while trying to fix the issue, probably just bc of my lack of experience.

Client from Unity, Host from Build.

First of all, in ContainerItemDisplay.cs we create a TempPivot, which we set as a child to our needed display, if we do it with both players ready, everything is okay, it's synced, but with late join this points don't exists for a client
![image](https://github.com/RE-SS3D/SS3D/assets/56740136/05c09637-3277-43a9-85bf-d969242f2c80)
but if you drop and pickup item, new TempPivot is created and it syncs!
![image](https://github.com/RE-SS3D/SS3D/assets/56740136/22932a08-f402-4614-a2d3-94449727e055)

If I make it as a field with [SyncVar], the pivots will show on client side, but info about their parent and transforms don't sync
![image](https://github.com/RE-SS3D/SS3D/assets/56740136/443b536f-f8be-4e73-973f-56de1dd016ba)
![image](https://github.com/RE-SS3D/SS3D/assets/56740136/e1bd6499-aead-4312-a0b8-4669644d3771)
![image](https://github.com/RE-SS3D/SS3D/assets/56740136/eea0cadd-6849-43d5-b325-b07c8bbdb09e)

Tried making it NetworkTransform, didn't really do anything, also tried giving PDAs and Boombox "Syncronize parent", but it needs parent to be the NetworkObject, but temporaryPoint is not. 
Maybe if I use prefab with NetworkTransform and NetworkObject to create temporaryPivot it would help? But honesly I think I just don't know what else to do and it start to sound funny.

I'm still sitting with this, and my lack of expirience fells very bad :v, but still trying!
Decided to write all of this, maybe you as more expirienced will get something from it?
