### ISSUE TITLE
Command should be called by clients and executed on server

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#1233]
## Summary

Currently, some commands (the console command popping when pressing F12) have to be launch from host (since it's also server), and it doesn't allow a client admin to execute commands such as spawning items server wise.
Find a way to allow authorized clients to execute commands server side.

## Possible solutions

Alain's suggestion : 

> you could mark a command as "run on server"
if the command parser on the client gets a command with that info, it sends the whole command string to the server
the server uses the same parser and actually executes the command

IamTeapot suggested to use a decorator (need more info)

**Comment by xk0fe** [comment]
Why not send command request to the server, server verifies admin rights of a sender and then executes the command?

**Comment by stilnat** [comment]
that's the idea, the only thing I'dd add is the possibility to execute command on clients in some cases, PR #1234 should solve this issue
