### ISSUE TITLE
Tilemap second iteration

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#1249]
# Connecting and Placing simple tile objects

This iteration focus on connectors and correct placement of objects on the tilemap. The next iteration should focus on tools to make building the map easier. It should also provide a correct architecture to easily add new connectors in the future.

## Placing multiple object per tiles.

- [x] Have the possibility for each layer to handle multiple tile objects.
- [x] Should have the option between 1 or 4 for now.
- [x] Have the system extensible so it can support different amount in the future.
 
## Fixing connectors

- [x] Cutting the multiAdjacency connector in multiple single responsibility connector scripts.
- [x] Fixing existing connectors to make them work (pipe, door, walls) ...
- [x] Adding the disposal pipe connector, making it work with vertical mesh.

**Comment by cosmiccoincidence** [comment]
Does the WIP in the title imply that these issues are already in progress or that you are going to add more details to this issue?

Same question for #1251 as well...

**Comment by stilnat** [comment]
not in progress, just there to remind us we need to write it correctly.

**Comment by cosmiccoincidence** [comment]
Closed by #1269 & #1274
