### ISSUE TITLE
Import examine system

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#1257]
## Summary

On the outdated branch, we used to have a pretty neat examine system. We'd like to have it back. Examine is using at its core a shader based method to select items as opposed to the classic collider based method. This method is ideal both to examine and to perform any other kind of interactions really. 

The difficulty resides in the fact that the import won't be straightforward, it needs to be reworked to get some performance improvements (not too bad, but still not great yet.)

## Docs

Some concerns were raised in a previous attempt, you can find them here : 
https://github.com/RE-SS3D/SS3D/pull/842

and here : 
https://github.com/RE-SS3D/SS3D/pull/839

Regarding performance, there might be some inspiration here :
https://medium.com/@philippchristoph/pixel-perfect-selection-using-shaders-16070d3094d

Here's ryan doc on the examine system 
https://docs.google.com/document/d/1xTyRXzi1g7H3SOkw1wkrFFbMcDUA0VEE/edit

## Goal

The PR solving this should check the following : 

- [ ] objects are examinables behind colliders, as long as they are visible
- [ ] This task is critical in terms of performance, performance should be correctly measured and documented on this.

**Comment by Ryan089** [comment]
Assign me.
