### ISSUE TITLE
Add Lights to Tilemap

### ISSUE THREAD

**Issue by TimFinucane** [RE-SS3D/SS3D#126]
Add lights to the tilemap, they should be able to go on any wall.

Also add a system to ensure that lights can't go on anything but a wall, and apply same system to any other fixtures that already exist (such as tables, which must go on a floor).

**Comment by cosmiccoincidence** [comment]
Also lights should have a setting in the tilemap editor to select a facing direction (similar to airlocks but with all 4 cardinal directions).
