### ISSUE TITLE
In-game Settings

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#1281]
## Summary

Add functional in-game settings.

## Goal 

In-game settings should be client based. These settings will be found in the "Game Settings" tab of the game menu. Also, the settings themselves should be toggleable both before and/or during a round.

In the future there will likely be many game settings that will be divided into sections based on type. For now, lets add just one section, "User Interface". And we will add two toggle options, 1 for toggling the stamina bar and 1 for toggling the server ping data.

See image for example. (The UI doesn't need to be perfect, it will likely undergo improvements overtime)

![Unity_tCboQUOXcP](https://github.com/RE-SS3D/SS3D/assets/41941008/f4ceba59-94a8-4fda-82ff-ac898481784c)

**Comment by stilnat** [comment]
it's not ping data, it's network traffic data. Should be "network traffic info". Ping info is not present yet.
