### ISSUE TITLE
Launcher doesn't work

### ISSUE THREAD

**Issue by iamteapot422** [RE-SS3D/SS3D#1292]
## Current Behavior

When you launch SS3D.exe only this screen appears with an unopenable error
![screen](https://github.com/RE-SS3D/SS3D/assets/77565416/a7d6d9b5-2007-475b-bff2-95db15a00ffc)

## Steps to Reproduce
Build the game and launch SS3D

**Comment by cosmiccoincidence** [comment]
Currently the game must be run via the .bat files in the parent folder.

**Comment by stilnat** [comment]
closed by PR  #1287
