### ISSUE TITLE
Limit rotation of build hologram on certain objects

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#1300]
## Summary

Limit the rotation of the construction hologram on certain objects to prevent unintended construction.

## Goal 

**NO ROTATIONS**:
- Plenums
- Floor Tiles
- Tables
- Walls
- Windows
- Girders
- Wires
- Disposals
- Pipes (non-offset)

**2 DIRECTIONS** (North & West I think):
- Offset Pipes
- Airlocks

**Comment by stilnat** [comment]
disposals need rotation. it's the direction they are placed in that determine in which direction they look when placed on the tilemap under some disposal furniture

**Comment by cosmiccoincidence** [comment]
> disposals need rotation. it's the direction they are placed in that determine in which direction they look when placed on the tilemap under some disposal furniture

Is that based of the disposal furniture's direction?
