### ISSUE TITLE
Clothes disappear at edge of screen

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#1312]
## Summary

Clothing disappears from player's that are at the edge of your screen.

## Steps to Reproduce

Make build, run host and client, move characters near edge of screen.

## Media

https://github.com/RE-SS3D/SS3D/assets/41941008/0290c5d1-8d58-4784-80d7-c29cf9bc4099

**Comment by stilnat** [comment]
That has to do with the way SkinnedMeshRenderer works :  

> Unity uses the mesh’s bounds to determine whether to render it. If the entire bounding volume
is outside the view of any active Camera
, Unity does not render the mesh.

We can easily change that in the skinned mesh renderers bound and have it not render when outside of the screen. Probably making the bound bigger would be enough to solve that.

More here : 
https://docs.unity3d.com/Manual/class-SkinnedMeshRenderer.html
