### ISSUE TITLE
Can see in/thru wallmounts

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#1313]
## Summary

Can see inside/thru of wallmounts when they overhang an end wall piece.

![image](https://github.com/RE-SS3D/SS3D/assets/41941008/11b69ab2-031e-4a6f-a061-456957512e09)

## Expected Behavior

Not this.

## Possible Solution

Add a plane to the back of the wallmount meshes to prevent seeing inside of them when sticking out past a wall (via modeling not code).

**Comment by stilnat** [comment]
isn't that a modelisation issue ? I don't think the added plane should be done by scripts, feels a bit messy to me.

**Comment by cosmiccoincidence** [comment]
> isn't that a modelisation issue ? I don't think the adde plane should be done by scripts, feels a bit messy to me.

Correct. If we go with method 1, it would need to be fixed by a modeler.

**Comment by stilnat** [comment]
then method 1 is by far the most reliable.

**Comment by cosmiccoincidence** [comment]
> then method 1 is by far the most reliable.

My main concern with this is that wallmounts can clip into each if we allow them to exist on end wall pieces.

![image](https://github.com/RE-SS3D/SS3D/assets/41941008/36176010-b1ef-4c1e-b911-4fd41c89fc9e)

**Comment by stilnat** [comment]
could add a check to see if there's already a wall mount anywhere in a 45 degree direction. Should not be too hard to add.

**Comment by cosmiccoincidence** [comment]
> could add a check to see if there's already a wall mount anywhere in a 45 degree direction.

I'm assuming you mean a 90 degree direction. But either way I'm not sure it would be this simple...

The clipping as seen in the image above only occurs with wide wall mounts (like air alarms, light tube, and posters) but doesn't occur with non-wide wallmounts (like light switches, light bulbs, & fire alarms). So the clipping won't always occur even when there are 2 wallmounts 90 degrees from each other.

Also, there may be instances where we intentionally want 2 wallmounts 90 degrees from each other. I'm sure you can find examples of this throughout ss13 maps.

**Comment by stilnat** [comment]
give the wall mounts two types, large and small, small fit in all cardinal directions, large can not get build adjacent  (90 degree) to another large mount.
