### ISSUE TITLE
Trying to delete a wallmount deletes all of them on that layer

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#1314]
## Summary

Trying to delete a wallmount deletes all of them on that layer.

## Steps to Reproduce

Lay multiple wallmounts on a single wall tile at different rotations.
Try to delete just one.

## Expected Behavior

Only the direction the hologram is rotated should be deleted.

**Comment by stilnat** [comment]
damn I thought this one was closed. Should not be too hard to fix though
