### ISSUE TITLE
Github CI tests are broken

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#1322]
## Summary

Tests automatically fail due to some issues with github actions. The tests have this warning in the logs
![image](https://github.com/RE-SS3D/SS3D/assets/14344825/a6a8a241-5ea4-4f4e-baf0-a974c48f9572)

Github made a note: 
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

Fix the CI tests please

**Comment by gouravmpk** [comment]
Assign me

**Comment by gouravmpk** [comment]
@stilnat if it doesn't work mention me I will look into it
