### ISSUE TITLE
Fix in hand interaction

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#1329]
## Summary
The outdated branch used to have in hand interaction working. Fix it.

## Current Behavior

Does not work.

## Expected Behavior

- Pick up a bikehorn
- Click on its sprite in UI when held in hand.
- honk honk.

## Possible Solution

Look at the outdated code and compare with now. the Inventory script is lacking the ClientInteractWithSingleSlot method, which call "InteractInHand". 

## Dependencies

wait for #1257 to be complete

**Comment by Ryan089** [comment]
I don't recommend doing this until #1257 is complete - it will likely conflict.
