### ISSUE TITLE
Attack particles duplicated

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#1332]
## Summary

each time a player is hit by pressing F while putting the mouse on them, an attack particle is instantiated. those particles should be quickly destroyed and not add up like that

![image](https://github.com/RE-SS3D/SS3D/assets/14344825/ac33fa6c-15d6-4f52-b9e5-a8b64a92f1b3)

**Comment by jckling** [comment]
use coroutine to destroy the object after 1 second, would it be a proper solution?

**Comment by stilnat** [comment]
@jckling yep good enough I think !
