### ISSUE TITLE
Body continues animation even after entity died

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#1351]
## Summary

Dead bodies seem to continue animating after the parent entity has died.

The only example I have tested myself is running and killing yourself at the same time.

## Steps to Reproduce

- start round
- start running
- killed self while running

## Expected Behavior

Dead bodies should not be animated (typically).

## Video

https://github.com/RE-SS3D/SS3D/assets/41941008/68fee6c4-637f-43bf-ac46-4eb36798f663

**Comment by stilnat** [comment]
remove animation, and even better, put the body in a ragdoll state upon dying
