### ISSUE TITLE
Cant search for items in tilemap menu

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#1363]
## Current Behavior

When you try to search for many items by name in the tilemap menu, they are not properly registering via search.

In the video I first go to the items page (not necessary) to show there are 2 gloves. I then try to search for gloves and the moment I type "g" and only one glove shows up, I continue writing the word "glove" and it no longer shows up.

https://github.com/RE-SS3D/SS3D/assets/41941008/c5fa9555-a0c1-48f5-9fe5-13b2010519c9

## Steps to Reproduce

Open the tilemap menu using <kbd>b</kbd> and go to the items page and look for an item then trying searching for it in the search bar.

## Solution

- Remove case sensitivity for search.
- Remove "namestring" field in scriptable objects and replace with object (file) name.

**Comment by cosmiccoincidence** [comment]
Apparently the search is case sensitive so by searching "Glove" you are able to find the gloves.

**Comment by stilnat** [comment]
search case is sensitive and is using the "name string" of the items scriptable objects. Please remove that field and replace it with simply getting the game object name to complete this issue.

![image](https://github.com/RE-SS3D/SS3D/assets/14344825/212ca92e-6eb9-4ad0-8438-98ea93994959)

**Comment by jckling** [comment]
`nameString` in `ItemObjectSo` is inherited from `GenericObjectSo`, should it be removed in `GenericObjectSo`? 

If should, also need to change these to use object name

![image](https://github.com/RE-SS3D/SS3D/assets/25079277/070427f0-7c18-46b9-aa63-98bc9a32b3f9)

**Comment by stilnat** [comment]
@jckling yes it should, thanks for pointing that out. Maybe keep name string but as a property, returning the prefab's name.
