### ISSUE TITLE
Airlocks bugs out for a moment when it closes

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#1374]
## Summary

Airlocks bugs out for a slight moment when it closes.

Please fix.

## Steps to Reproduce

Play game. Open airlock and watch it close.

## Possible Solution

Havent looked into enough yet, but might just be that the animation timing is off a bit.

**Comment by jckling** [comment]
I found uncheck `Write Defaults` in animator can solve the bug 🤔 

![image](https://github.com/RE-SS3D/SS3D/assets/25079277/4109e195-0907-479a-a93a-c3e29c9edb97)

**Comment by cosmiccoincidence** [comment]
Have you tested this?

**Comment by jckling** [comment]
Yes, the animation is correct, but not sure if there will be other effects, I don't really understand this parameter.

Refer to [Unity - Manual: Animation States](https://docs.unity3d.com/Manual/class-State.html)

**Comment by cosmiccoincidence** [comment]
> Yes, the animation is correct, but not sure if there will be other effects, I don't really understand this parameter.
> 
> Refer to [Unity - Manual: Animation States](https://docs.unity3d.com/Manual/class-State.html)

Yeah I'm not sure. I guess if the change fixes the issue we can make the change and if any other issues emerge from it we can then figure out how to handle the situation from there.

**Comment by jckling** [comment]
OK, just uncheck this property to fix the bug
