### ISSUE TITLE
Skinned meshes not using hologram material when trying to build

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#1380]
## Summary

Objects using the skinned mesh renderer are being shown as normal objects when placing them using build menu. They should be shown using the hologram material like the other objects when trying to build them.

## Steps to Reproduce

- open build menu (b)
- try to place an tile object that has a skinned mesh (SMES, SolarPanel, PacmanGenerator)

**Comment by cosmiccoincidence** [comment]
Will try to look at that today. 

Narrowed down the problem, updating the issue.
