### ISSUE TITLE
Search text remain in tilemap menu when reopen and not display search result

### ISSUE THREAD

**Issue by jckling** [RE-SS3D/SS3D#1383]
## Summary

Search text remain in tilemap menu when reopen and not display search result

## Current Behavior

The search text typed in search bar does not be cleared or applied when reopen the tilemap menu

## Steps to Reproduce

1. Open the tilemap menu using `b` and type any text in the search bar
2. Close and reopen the tilemap menu

https://github.com/RE-SS3D/SS3D/assets/25079277/21f416a3-8ba4-4fdd-a3d7-59ac35ce02f4

## Expected Behavior

Clear the search text or display the search result

## Possible Solution

Clear the input field when open the menu, or apply search if text not empty

**Comment by cosmiccoincidence** [comment]
Clear input field imo.

**Comment by jckling** [comment]
I think so
