### ISSUE TITLE
Walls (and girder) are facing opposite from the right direction

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#1414]
## Summary

![image](https://github.com/RE-SS3D/SS3D/assets/14344825/3f86e77f-b320-4f49-bba7-20c6d91574d9)

It seems there's been some issue recently with the way walls and girder connect. They are facing the opposite direction when connecting.

**Comment by stilnat** [comment]
problem is actually more general, it seems to be an issue with all things connecting using the advanced adjacency connector.

![image](https://github.com/RE-SS3D/SS3D/assets/14344825/1b2030ec-7c8b-434c-a97c-820b2139a3cf)

**Comment by cosmiccoincidence** [comment]
I'm skeptical. It was working a few days ago when I made the new maps. It was working fine when I did a quick test before making the new release.
