### ISSUE TITLE
If you construct a 3x3 table, the middle part looks weird

### ISSUE THREAD

**Issue by Em3rgencyLT** [RE-SS3D/SS3D#143]
![image](https://user-images.githubusercontent.com/15195221/73611940-1715e580-45f0-11ea-8c1e-90cc5dff2cc6.png)

**Comment by TimFinucane** [comment]
Yeah that's a problem first and foremost with the table models, which need to be fixed

**Comment by cosmiccoincidence** [comment]
What's the problem with the table models? Didn't we complete the set of tables?

**Comment by TimFinucane** [comment]
As you can see in the image, some of the faces on the middle table mesh seem to be missing. Once those faces are put back in I can correctly configure which table mesh goes where.

The same face problem seems to exist with all X-type table meshes.
