### ISSUE TITLE
Make vendor machines and Jukebox work with electricity

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#1438]
## Summary

Currently vendor machines and jukebox are working independently from the electricity system. Goal is to make them work with it.
Maybe they can make a small sound when they turn on and off, and they should be functionnal only when they consume electricity.

**Comment by cosmiccoincidence** [comment]
Is there a systems document for electricity? Was gonna link it here but couldnt find it.

Design doc: https://ss3d.gitbook.io/design/environment/electricity

**Comment by stilnat** [comment]
Not yet, in the meantime, one can check how the lightbulbs work to get an idea of how to add electric consumers to the network
