### ISSUE TITLE
It is possible to build yourself and others into a wall/table

### ISSUE THREAD

**Issue by Em3rgencyLT** [RE-SS3D/SS3D#144]
Construction does not check if a tile is occupied by a player. Thus, you can literally build on top of yourself. Should probably also check for other objects in the way as well. There is probably no quick solution to this and a more robust system is required to handle these checks. This issue created as a reminder.

**Comment by TimFinucane** [comment]
I'd like to close this, as the current building mechanic is only temporary. Once it is replaced by a multi-stage building solution (construct a frame, fix it on a tile, add things to it), collision will be automatically considered.

**Comment by cosmiccoincidence** [comment]
Agreeing with Tim on this, gonna close this.
