### ISSUE TITLE
Construction Timer

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#167]
### Summary

Add timer to construction/ deconstruction. Currently only walls and tables. 

### Goal 

A timer should be added to the construction a deconstruction of walls and tables so it's not instantaneous.

**Comment by TimFinucane** [comment]
Any code for this should be generic enough to be attachable to other interactions

**Comment by onebigames** [comment]
To me, a timed interaction sounds close to a continuous interaction. Food for thought

**Comment by TimFinucane** [comment]
A continuous interaction requires the mouse to be held down. A 'timed interaction' is merely one where code is called some time after the click.

**Comment by onebigames** [comment]
I would argue a continuous interaction is one which has a condition that if true, cancel it.
A timed interaction would be a continuous one, with as condition example could be to not move or be moved, and after [time] the interaction resolves and does whatever it does.
