### ISSUE TITLE
Add Airlock Lights

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#168]
### Summary

Add lights to airlocks

### Goal 

The lights on airlocks currently aren't working. The Lights should turn emissive green for a brief moment when the door opens but turn back to normal by the time the door is fully opened.

**Comment by TimFinucane** [comment]
One idea I had earlier was that these could be part of the animation controller, if possible. This would make it easy to tie certain colours to certain animations (opening, closing, access denied)

**Comment by cosmiccoincidence** [comment]
closed by #182
