### ISSUE TITLE
Round Timer is Broken

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#180]
### Summary

The round timer is broken.

### Current Behavior

Watching the round timer in-game you will see it climb over-time, but when it reaches 3:34 it stops climbing and starts to decrease over-time.

### Steps to Reproduce

Launch game, watch timer.

### Context

[VIDEO](https://streamable.com/grctbj)

**Comment by TimFinucane** [comment]
this is quite funny if true
