### ISSUE TITLE
Interaction Distance on All Interactions

### ISSUE THREAD

**Issue by TimFinucane** [RE-SS3D/SS3D#184]
# Summary

All interactions should by default be limited to within a certain range. This should be done in the interaction handler and should be modifiable in the unity editor. By default it should be 1.5f.

You do not need to have an opt-out or override for individual interactions, we will do that later if needed.

**Comment by cosmiccoincidence** [comment]
Won't there be special cases where interactions will have varied distances (ex. Telekinesis). How will that be handled?
