### ISSUE TITLE
Client-side airlock networking failure.

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#191]
### Summary

Networking issue with airlocks for clients. Hosts work fine.

When the client opens an airlock they will not see it open (despite the fact that the host can see it open) and cannot walk through it.

Also when the host opens an airlock, the client cannot see it open.

[VIDEO](https://streamable.com/nrka56)

**Comment by Alainx277** [comment]
This specific issue seems to be fixed, can it be closed (just wasted some time trying to repoduce it)?

**Comment by cosmiccoincidence** [comment]
Sorry about that, it was literally fixed ~12 hours ago when #202 merged. This issue should have auto-closed with #202, not sure why it didn't.
