### ISSUE TITLE
Basic Crafting Interaction

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#194]
### Summary

Implement basic crafting.

### Goal 

The most basic form of crafting, specifically using a metal sheet and crafting a chair or stool for starters.

### Design

Pending.

### Other

You will likely need the metal sheet 3d model, but the seats may already be in. Either way, ping me if you need assets for this.

**Comment by TimFinucane** [comment]
We should design a crafting system before this surely?

**Comment by cosmiccoincidence** [comment]
You're probably right.
