### ISSUE TITLE
Bolt/Unbolt Interaction

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#195]
### Summary

Implement a bolt/unbolt interaction.

### Goal 

An interaction that allows the player to bolt/unbolt certain furniture to/from the floor. The bolting action effectively locks/unlocks the furniture's location and thus allowing/disallowing it to be moved.

### Related

If a furniture IS bolted than it should not be pull-able (#196).

**Comment by TimFinucane** [comment]
Should only apply to furniture which is somehow marked as Boltable.
