### ISSUE TITLE
Airlock & ID Interaction

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#197]
### Summary

Add an interaction where airlocks check for an ID before opening.

### Goal 

- Add IDs if they are not added already.
- Have airlocks check the player's inventory for an ID (any ID is fine for now) before proceeding. If the check finds an ID the door opens, if it doesn't find an ID it stays shut (preferably the airlock lights flash red briefly).

### Other

Ping me if you need assets for this.

**Comment by TimFinucane** [comment]
Does the ID need to be in the player's hands?

**Comment by cosmiccoincidence** [comment]
It should check the player's inventory and hands. If it finds it in either place it will open the airlock.

Eventually, when we have clothing and such, we will limit it from checking all of the player's inventory to just the ID or belt slots.

**Comment by corp-0** [comment]
do you guys have an interaction framework like we do in Unitystation? If so, I'd like to take this task.

**Comment by joaoburatto** [comment]
> do you guys have an interaction framework like we do in Unitystation? If so, I'd like to take this task.

kinda, we have the interaction system that can be easily used to implement this.
If you want to do a simple version considering the ID card in your hand, it'll be easier than trying to make the version where it finds your ID card in the inventory.
Check previous interactions to see how it works and ask me (john) on Discord if you need any help.

**Comment by cosmiccoincidence** [comment]
Sorry for the late reply we have been focused on redesigning lately. Making sure the systems we design will all be future proof. The interaction system is one of those, which we may be doing some rework too fairly soon. So it might be ideal to wait on this until after the rework.

**Comment by corp-0** [comment]
Awesome, doing reworks for futureproofing is always a good idea. I will stay expectant and see how it goes.
