### ISSUE TITLE
Weird lighting on client

### ISSUE THREAD

**Issue by TimFinucane** [RE-SS3D/SS3D#204]
# Summary

Something weird going on with client, where lighting bleeds through objects.

# Steps to Reproduce

Run on standalone client, start the game.

![lightbugs](https://user-images.githubusercontent.com/19370049/81163614-250a4680-8fe3-11ea-8433-911bb9803b27.png)

### Expected Behavior

See the in-editor game for expected behaviour

**Comment by cosmiccoincidence** [comment]
Not only does light bleed through walls but the player is also missing it's shadows it seems.
