### ISSUE TITLE
Airlock open interaction when close by

### ISSUE THREAD

**Issue by Alainx277** [RE-SS3D/SS3D#225]
### Current Behavior

When standing right next to an airlock it is possible to close it.
When trying to open it, the interaction does not show up.

### Steps to Reproduce

1. Stand next to an airlock
2. Close the airlock by clicking
3. Try to open the airlock by clicking

### Expected Behavior

The airlock should open on interaction, even when standing close to it.

### Possible Solution

I am not sure what the problem is. I think it could be with the raycast peformed, as CanInteract on a door is always true.

**Comment by cosmiccoincidence** [comment]
I was NOT able to replicate this... Manually opening/closing airlocks works fine for me on both hosting and non-hosting client.

**Comment by Alainx277** [comment]
Weird, might be something with my setup.
Closing for now
