### ISSUE TITLE
Toggle flashlight bulb material with flashlight state

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#232]
### Goal 

The material on the bulb of the flashlight is set to the 'Palette05 Emission' material currently. It should toggle between 'Palette05 Emission' (when the flashlight is on) and 'Palette05' (when the flashlight is off).
You can use the class MaterialChanger that has a list of materials.

**Comment by primebie1** [comment]
claiming this one

**Comment by Ashes2007** [comment]
Going to try this.
