### ISSUE TITLE
Containers not working

### ISSUE THREAD

**Issue by LightVelox** [RE-SS3D/SS3D#264]
### Summary

Currenctly storing containers has three problems:
1- ~~You can open the container and go very far and will still be open~~ #238 
2- Storing items on them will freeze them in mid air #216
3- Trying to take the item will break the container UI, creating duplicates of the item, and also make the item unattainable #269 
4- Dragging and item from the right hand slot will transport it to the left hand slot until you stop dragging, where it will go back to the correct slot #271 
5- After an item was glitched in a container like mentioned in 3, if you click the item it vanishes from the game scene and breaks the slot, making it unusable 

### Current Behavior

There are some container right now, like the Fridge, storing an item inside them create numerous visual glitches and basically removes the item from the player's reach, since he can't take them from the container anymore, also putting items inside container currently breaks the slot they are put in

### Steps to Reproduce

1- Take an item with your right hand
2- Drag it to anywhere that isn't a slot(glitch 4)
3- Open a container and drag it into any slot(glitch 2 and 3)
4- Click the item in the container slot(glitch 5)
5- Congratulations, you not only lost your item but also corrupted the container's slot

### Expected Behavior

Putting and taking items from the container without either visual glitches or breaking the item

**Comment by cosmiccoincidence** [comment]
This 1st one here is similar to #238
