### ISSUE TITLE
Dropping item disables components

### ISSUE THREAD

**Issue by henkhooft** [RE-SS3D/SS3D#270]
### Summary
Dropping items breaks custom functionality set in components like scripts or audiosources

### Current Behavior
The inventory system disables items when stored in a container or when in hand. When placed back into the world, the item is made active, but not all Components are activated again. This breaks items that have active scripts or other components like the Honk.

The inventory system does seem to enable some components (boxcolider) when placed back into the world. 

### Steps to Reproduce
Grab the Honk from a desk. Honk a few times. Drop the honk and pick it up again. Try honking again.

![afbeelding](https://user-images.githubusercontent.com/5231626/82118810-d8103800-9779-11ea-9c0f-485935bd7d70.png)

### Expected Behavior
Placing items back into the world should enable all components (scripts, AudioSources, etc).

**Comment by Alainx277** [comment]
Just debugged this, it is caused by deleting the parent gameobject. No idea how this is related but setting the parent to null before deleting it makes the bug disappear.
