### ISSUE TITLE
Camera doesn't work after relogging

### ISSUE THREAD

**Issue by LightVelox** [RE-SS3D/SS3D#276]
### Summary

After the round ends and the login screen appears, correctly logging in and selecting your character will spawn him, but the camera will not work as intendend

### Steps to Reproduce

Open the game
Wait for the round to end
Login in and select your character

![Anotação 2020-05-16 160522](https://user-images.githubusercontent.com/28792244/82128134-2976f200-978f-11ea-8151-1b661294f542.png)

### Expected Behavior

The camera should work both when the round starts and restarts

**Comment by cosmiccoincidence** [comment]
Unable to replicate this now... might have been fixed at some point closing it for now. If the bug persists feel free to reopen this.
