### ISSUE TITLE
Container Size

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#295]
### Summary

We need a way to differentiate different sizes of containers in-game.

### Goal 

The goal here is to designate different size containers maybe through flags or other means. Three reason for this is so once we start adding the container script to items like medkits and toolboxes, you shouldn't be able to put 1 toolbox inside the other, but you SHOULD be able to put a toolbox in a locker.

**Comment by onebigames** [comment]
This should in the long term be resolved by calculating the material composition of the container against the volume of the container component

this would look like : 
a locker can contain 50L of nondescript stuff, and it is composed of 20Kg of metal
we then calculate what is the volume of the locker in and of itself (not the volume it can contain) by adding the volume of his materials (e.g 20Kg of metal = 30 Liters), making the locker an object taking 50L(what it can contain) + 30L(his own volume) of size
the final calculation makes it impossible for a locker to contain another, it will also come very usefull when calculating item resistance and general atmos work if i'm not misled
