### ISSUE TITLE
Double tapping E bugs camera rotation

### ISSUE THREAD

**Issue by TaylorNAlbarnaz** [RE-SS3D/SS3D#297]
### Current Behavior

Double tapping to rotate the camera should just rotate 180 degrees, but it goes back 90 degree for some reason

### Steps to Reproduce

Press E twice fast, just twice, pressing it a bunch of times may not give a problem

### Expected Behavior

Double tapping E should rotate the camera 180 degrees to the right

**Comment by cosmiccoincidence** [comment]
The camera rotation controls were changed from 'Q' and 'E' to 'CTRL + Q' and 'CTRL + E' but the principle of this bug should remain.

This bug does need testing/confirmation again though.
