### ISSUE TITLE
Drinking Interaction

### ISSUE THREAD

**Issue by LightVelox** [RE-SS3D/SS3D#341]
### Summary

Implements a drinking interaction

### Goal 

Different from eating, it should not consume the item, just reduce the amount of liquid inside it, for now we don't need beakers and digestions or anything so for now just have a int or float value called "amount", just a fixed amount a cup or soda can has, and the Drink interaction should reduce it until you can't drink anymore, also playing the "Drink" sound

**Comment by cosmiccoincidence** [comment]
Closed by #499
