### ISSUE TITLE
Interaction is highlighted even when no interaction is selected

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#362]
### Summary

The top interaction starts highlighted despite no interaction being selected yet. Also the highlight does not disappear if the user selects one then deselects.

### Steps to Reproduce

- right click something for the interaction wheel to appear (look for something with multiple interactions_
- see the first interaction is highlighted but it has not been selected yet
- mouse over a interaction to select it, then move your mouse back to the center to deselect
- see the highlight remains even after the deselection

**Comment by LightVelox** [comment]
It's not really a bug, it's cause the radial selection wheel is always shown, it's just rotated when something is selected, a way to fix that is to change the transparency to 0 when there is nothing selected
