### ISSUE TITLE
You can build tables inside the player

### ISSUE THREAD

**Issue by LightVelox** [RE-SS3D/SS3D#366]
### Summary

You can currently build a table "inside" the player, it doesn't check if there is a player in the current fixture

### Steps to Reproduce

1- Pick a wrench
2- Go to a empty tile
3- Click on the tile you're in

### Expected Behavior

Building interactions should only work when there is no player on the current tile

### Media
![Anotação 2020-05-31 141603](https://user-images.githubusercontent.com/28792244/83358402-9a9ad580-a349-11ea-9983-618aca1991a0.png)

**Comment by cosmiccoincidence** [comment]
This bug is back, I believe due to the tilemap rework.
