### ISSUE TITLE
Basic Crafting is Broken

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#370]
### Summary

The basic crafting/cooking system implemented in #331 is broken. You should be able to roll dough flat or cut it into strips, but currently, it does not seem to work.

### Steps to Reproduce

Try using the knife or rolling pin on the dough, nothing happens.

**Comment by Alainx277** [comment]
This is due to a bug introduced by changing the pickup interaction. It is fixed in #361.
It is still possible to roll it out, but it has to be done in the radial menu.
