### ISSUE TITLE
Placing objects on top of walls

### ISSUE THREAD

**Issue by EikoBiko** [RE-SS3D/SS3D#381]
### Summary

In some instances, you are able to place objects on top of walls.

### Current Behavior

If you have an item in your hand and you click the top of a wall, it places it on top of the wall.

### Media

![bug](https://user-images.githubusercontent.com/53350053/83928934-7ed76b00-a75f-11ea-8bd9-373148befdd9.gif)

### Expected Behavior

You should not be able to place objects on walls.

**Comment by cosmiccoincidence** [comment]
Happens on vending machine and similar machines too.

**Comment by joaoburatto** [comment]
apparently you can still do that sometimes.
