### ISSUE TITLE
Janitor cart items lock up hand space

### ISSUE THREAD

**Issue by EikoBiko** [RE-SS3D/SS3D#382]
### Summary

When grabbing an item from the janitor's cart, the item occupies the hand space, but cannot be used, or dropped.

### Current Behavior

The object occupies the hand space, but does not get placed into the hand.

### Media

![bug2](https://user-images.githubusercontent.com/53350053/83929316-e6da8100-a760-11ea-9759-3e05e4051aa6.gif)

### Expected Behavior

The object should be removed from the cart and placed into the hand of the player. Then, the player should be able to drop the item.

**Comment by Alainx277** [comment]
This due to an assumption in the container handling code that all items have colliders and rigidbodies. In this case the items should have those components added.

Attaching a console log is helpful if an error is logged, for future issues.

**Comment by cosmiccoincidence** [comment]
The egg box does something similar too.
