### ISSUE TITLE
Cell Charger Display

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#399]
### Summary

The power cell charger should display how much charge the connected power cell has. 

### Goal 

Make the cell charger lights turn on in relation to the charge of a connected cell.
0%-10% = None
10%-35% = Red
35%-65% = Red + Orange
65%-90% = Red + Orange + Yellow
90%-100% = All

This may require either separating the lights into separate objects or adding a shape key to the charger.

**Comment by cosmiccoincidence** [comment]
Related to #398

**Comment by Ryan089** [comment]
Task reserved for StenBone.
