### ISSUE TITLE
Doors opening when walked away from.

### ISSUE THREAD

**Issue by EikoBiko** [RE-SS3D/SS3D#40]
To recreate:

Approach the door to make it open.
Click the door to make it close.
Walk away, and the door will open.

**Comment by TimFinucane** [comment]
This seems to be a result of the chosen functionality: When the user enters or leaves a square adjacent to the door, the door opens/closes (regardles of the direction the user is facing).

Whats the best functionality for this? I'm thinking:
If the user is in a square adjacent to the door, is moving towards the door, and the door is closed, then the door opens.
When the door opens, it closes after 3 seconds (regardless of what user does).

How does that sound?

**Comment by onebigames** [comment]
the commit referenced right here seem to have fixed this issue temporarily.
thanks you for your suggestion TimFinucane, but the current doors are really temporary, so until we finish some other features i think we will keep a naïve sense to them.
