### ISSUE TITLE
Extend pipe machinery

### ISSUE THREAD

**Issue by henkhooft** [RE-SS3D/SS3D#422]
### Summary
The first implementation of pipes added some basic pipe machinery. Now it is time to extend these and add some important SS13 atmospherics machines.

Already existing:

- Manual valve
- Volume pump
- Pressure pump
- Gas Mixer
- Gas Injector

### Goal 
Still to be added:

- [x] Gas filter

- [x] Unary vent

- [x] Scrubber

- [ ] Canister ports

- [ ] Meter

Integration with Air alarms is not necessary for now

**Comment by cosmiccoincidence** [comment]
Keep in mind you can have smaller pipe machines (ex. pumps, valves, etc) on all layers on a tile, but larger pipe machines (ex. filters, mixers, etc) cannot.
