### ISSUE TITLE
Integrate AtmosObject with the tilemap

### ISSUE THREAD

**Issue by henkhooft** [RE-SS3D/SS3D#423]
### Summary
In the current situation every tile can contain an AtmosObject, however they are only created at runtime with a default air mixture. Integrate the AtmosObject with the tilemap so that we can set a gas mixture already in the editor.

### Goal 
- [ ] Make AtmosObject serializeable to allow setting it in a Tile. Set a default air mixture for tiles that do not have a preset atmosobject.

- [ ] Add the option to preset a gas mixture for an AtmosObject

- [ ] Add the option to preset the temperature

- [ ] Have a few popular presets in the editor. (air mixture, vacuum, pure oxy/co2/plasma)

**Comment by cosmiccoincidence** [comment]
Should be taken care of in #628 / #682
