### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by TimFinucane** [RE-SS3D/SS3D#43]
There is a memory leak somewhere causing massive unbounded memory increases.

To recreate:
- Run game (either in unity or build & run)
- Click LAN Host (so that a map/user is loaded)
- Watch in task manager or equivalent for memory increases.

It only occurs when actually playing the game, not when in the menu screen.

**Comment by TimFinucane** [comment]
BTW the issue is identified (but not fixed). It's the MaterialChanger implicitly copying a MeshRenderer's materials, which then isn't garbage collected for some weird unity reason (https://docs.unity3d.com/ScriptReference/Renderer-materials.html)

However it's my opinion that material changer should be removed entirely - any visual changes to models should be animation or state-machine driven rather than being in the logic code.

**Comment by phantomfears** [comment]
Does MaterialChanger get used anymore? CodeLens shows 0 references and deleting the file does not generate errors.

**Comment by phantomfears** [comment]
MaterialChanger is no longer referenced anywhere it seems.

**Comment by TimFinucane** [comment]
This should be correct yeah, I've been slowly moving use away from it. Thanks for checking this! Am going to close since this is no longer a problem.
