### ISSUE TITLE
Getting up from ragdoll

### ISSUE THREAD

**Issue by joaoburatto** [RE-SS3D/SS3D#450]
### Summary

Our current getting up system works with resetting of every bone to the idle position, which shouldn't be the case at all, for that we need a dynamic getting up system, being it animation or pure physics.

### Goal 

Make ragdolling and player movement dynamic and fluid.

### Media

[Example on how it should look, but a lot faster](https://www.youtube.com/watch?v=MAAOqNon7cU)

[Another example, a lot better](https://www.youtube.com/watch?v=pk0nVmWTwuM)

[Less desirable but whatever works](https://www.youtube.com/watch?v=sjRE4qW_giU)

### Document

In the future we will also have broken bones in the character, so that should also be remembered while working on it.

### Dependencies

 #325 should be worked on before this.

**Comment by Alainx277** [comment]
This could be done by having 2 getting up animations (belly and back).

1. Calculate if ragdoll is lying on it's back or belly
2. Choose appropriate animation
3. Lerp to first frame in animation
4. Play animation

**Comment by cosmiccoincidence** [comment]
This will likely need #326 done first or done with this...
