### ISSUE TITLE
Can't get up after ragdolled 

### ISSUE THREAD

**Issue by joaoburatto** [RE-SS3D/SS3D#460]
### Summary

You can't get up after ragdolled if you drop the soap or banana in your hand while already ragdolled.

### Current Behavior

You won't get up after being ragdolled

### Steps to Reproduce

Pick up the soap/banana, drop it.
While ragdolled pick it up and drop it again.

### Expected Behavior

You actually get up

**Comment by Alainx277** [comment]
When the item is picked up the game object is disabled. This causes all co-routines to be stopped, preventing the player from getting up.
