### ISSUE TITLE
Cannot Examine Objects on Janicart

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#464]
### Current Behavior

The player cannot examine items on the janitor cart.
This is mostly due to the janitor cart's collider blocking the items.
There is a secondary problem which is the children prefab items on the janitor cart are not updated with the main prefabs for those items due to the fact the children prefabs are unpacked and missing some scripts to prevent them from colliding with the janicart itself.

### Expected Behavior

The items on the janitor cart should be examinable separately from the items on it.
Alternatively, the janitor cart items should show up in the description when examining the cart.

**Comment by cosmiccoincidence** [comment]
Similar to #462 & #463

**Comment by Ryan089** [comment]
While I had thought this issue had been resolved, I noticed a **very** strange effect on the Mop Bucket when examining in v0.3.95e. I'll look into this.

**Comment by cosmiccoincidence** [comment]
> I noticed a very strange effect on the Mop Bucket when examining in v0.3.95e. 

This?

![RESS3D_ZXQL9vIwXd](https://user-images.githubusercontent.com/41941008/124357731-10c3d880-dbeb-11eb-856e-7f379a87e667.png)

I noticed it too.

Also, we need to figure out how to handle the objects that are on the Janitor Cart. Currently, I think the rigid bodies on the items are glitching with the janicart itself and causing the items to fly off the cart and on to the floor (not part of this issue though).

**Comment by Ryan089** [comment]
Other items known to be affected by the visual display bug are the Sink, Hydroponics Tray and Seed Processor. As far as I can tell, this issue **only** occurs in the compiled executable, and does not occur in the Unity editor.

**Comment by cosmiccoincidence** [comment]
It's worth checking to see if these objects all use skinned mesh renderers as opposed to the standard mesh renderer.
