### ISSUE TITLE
Items Glitch on Player Collider when Dropped

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#469]
### Summary

When the player drops an item, it oftentimes violently collides with the player or gets stuck on the player until they move.

### Steps to Reproduce

Drop and item.

### Expected Behavior

The item falls to the ground without being affected by the player's collider.

**Comment by nalewis** [comment]
Some evidence that this issue is still present:

https://user-images.githubusercontent.com/22083562/148496949-967d68b8-3d9f-42e0-9ec8-03bdf4583807.mp4
