### ISSUE TITLE
Item is dropped when put into Disposal bin

### ISSUE THREAD

**Issue by konstantin3002** [RE-SS3D/SS3D#473]
### Summary

Item that should be put into the bin are dropped instead, but behave as being in a bin.

### Current Behavior

Item is dropped AND located in the Disposal bin at the same time. Can be seen in detail in this video:
https://www.youtube.com/watch?v=TABiA_Xqzz0&feature=youtu.be

### Steps to Reproduce

1. Take an item in hand
2. View container of the Disposal bin
3. Drag an item from hand into container slot

### Expected Behavior

Item disappears from hand and is now located in the Disposal bin container inventory slot 

### Possible Solution

Items should probably be deleted from the hand slot after inserting them into Disposal bin and not dropped.

### Context
Build June 2020 Monthly
Win10 Home

**Comment by cosmiccoincidence** [comment]
May be related to #515
