### ISSUE TITLE
Create a custom character controller

### ISSUE THREAD

**Issue by LightVelox** [RE-SS3D/SS3D#494]
### Summary

Right now the player is controlled by a CharacterController, which prevents us from adding a RigidBody, which also means poorer physics interactions, right now the player can easily push a 1000 kilos locker, has no mass at all and so on, the player should have a Rigidbody component and be controlled by the HumanoidMovementController script.

### Goal 

Remove the CharacterController component
Make the player movement work with a Rigidbody

**Comment by Ryan089** [comment]
After consideration, it was decided that Rigidbodies were not the preferred method of controlling the character.
