### ISSUE TITLE
Fix topology on vending machines

### ISSUE THREAD

**Issue by joaoburatto** [RE-SS3D/SS3D#523]
### Summary

The geometry needs a retopology, it's causing shading issues, YouTool and Cola seems to be ok though.

### Goal 

Fix shading issues.

### Media

![image](https://user-images.githubusercontent.com/46575243/87257734-da3dfc80-c473-11ea-875e-331e0aa5379a.png)

**Comment by cosmiccoincidence** [comment]
Some of the sizes are too big too. (The cigarette, soda & snack machines all go up to the top of the walls... they should be scaled on the vertical axis to 0.9

**Comment by cosmiccoincidence** [comment]
Where are the shading issues specifically? On the top or on the inside or where?

**Comment by cosmiccoincidence** [comment]
This was fixed in a recent model update.
