### ISSUE TITLE
Lighter Interaction

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#524]
### Summary

Right now the lighter opens and closed like many of the containers do, but really 1 interaction should open the zippo and light it, then using it again puts the flame out and closes the lighter.

### Dependencies

- this will eventually need unique VFX, but for now, you can re-use the welder flame.

**Comment by CrazyMalk** [comment]
Shouldnt this also happens to thing such as toolboxes? I feel like a single interaction should both open the toolbox model and the inventory.
