### ISSUE TITLE
Stunbaton icon is so small it cannot be clicked in play window

### ISSUE THREAD

**Issue by Shillelagh-Hummus** [RE-SS3D/SS3D#553]
Issue partially resolved if you maximize play window.
Upon picking up a stunbaton it cannot be clicked again since it's icon is so small.
Potential fixes:
Make the renderer scale images base on icon size
Make the context menu open when clicking in the occupied square.

**Comment by cosmiccoincidence** [comment]
Related to #572

**Comment by LightVelox** [comment]
This one was already fixed, should be closed

**Comment by cosmiccoincidence** [comment]
I think the problem persists with other items still tho.
