### ISSUE TITLE
Improve Item Icon Rendering

### ISSUE THREAD

**Issue by joaoburatto** [RE-SS3D/SS3D#572]
### Summary

Currently, we have a camera where items are rendered and transformed into images. Everything is rendered on **Start()**

### Goal 

Make sure items are rendered properly and have an easily identifiable icon.

### Document

Currently, there are two main problems:

1. Item's materials render weirdly, in the case of glass and emission they are either invisible or not rendered as wanted. 
_**Solution** (maybe): copy the post effects from the main camera to this new camera, if that doesn't work, we have to find a way to make the materials all the same._
2, Item's bounds make the camera render it in a weird position/angle, you can see that with the esword and the welder (both caused by the bound of the whole object, in the case of the esword, when it is off, it's bounds are the same as if it was on, while it is not that big of a problem its a problem, but with the welder, we have a particle system on it, so the bounds are pretty big.
_**Solution** (maybe): Two offset variables for angle/position or another way to measure the bounds._

**Comment by cosmiccoincidence** [comment]
Related to #591 & #535

**Comment by cosmiccoincidence** [comment]
Part 1 may be fixed in #861
