### ISSUE TITLE
Fixtures not synchronizing to client

### ISSUE THREAD

**Issue by henkhooft** [RE-SS3D/SS3D#606]
### Summary
The jukebox is not correctly synchronizing with the client.

![afbeelding](https://user-images.githubusercontent.com/5231626/107687941-641ea400-6ca7-11eb-9a37-6d18b5a5b079.png)

### Steps to Reproduce
1. Host a server and connect with a client
2. Interact with the jukebox on the server

**Comment by henkhooft** [comment]
Discovered that this actually affects all networked fixtures that are part of the tilemap. Reason is most likely a wrong netID because the tilemap is recreated for the connecting client

**Comment by cosmiccoincidence** [comment]
Hopefully gets resolved with #628 / #682
