### ISSUE TITLE
Ragdoll Manager

### ISSUE THREAD

**Issue by onebigames** [RE-SS3D/SS3D#62]
**Description**
Create a component that manage a group of ragdoll bones, it should :
- contain a list of its children bones
- contain a reference to an animator
- have a function to set the ragdoll interpolation level SetRagdollLevel(float newLevel) Note : (as the interpolation of the ragdoll is in another task, if it is not done just enable ragdolls when newLevel >= 0 )
- permit to flag bones as synchronised, and if they are sync them across the network

**User Story Link**
https://github.com/RE-SS3D/SS3D/issues/57

**Comment by jblac150** [comment]
This is Singulo. I am seeing an issue with not syncing all bones. For example, if I only sync the hips, spine, and head, leaving the legs and arms unsynced, they seem to flail around and even mess up the overall transform of the ragdoll itself, causing it to flop about, while the synced bones are still correctly in place.
Syncing all bones solves the problem though.
