### ISSUE TITLE
FPS drop when zooming in on character

### ISSUE THREAD

**Issue by henkhooft** [RE-SS3D/SS3D#620]
### Summary
The frames per second drops dramatically when zooming in on your character. Interesting enough, this only occurs with SSRT enabled. Disabling it actually improves FPS when zooming in.

![fps_drop1](https://user-images.githubusercontent.com/5231626/108764367-cb174500-7552-11eb-8a61-9d9908425c57.PNG)

![fps_drop2](https://user-images.githubusercontent.com/5231626/108764370-cbafdb80-7552-11eb-997b-66a9b06f522f.PNG)

### Steps to Reproduce
1. Start a game
2. Monitor your FPS
3. Zoom in and watch again

### Possible Solution
Next to SSRT being related, it may be linked to the FOV system

**Comment by Ryan089** [comment]
Hey @henkhooft, how do I get that statistics window?
