### ISSUE TITLE
Asset Data Management 

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#627]
### Summary

Implement Seteron's asset data rework.

Should maybe include a basic technical write-up in the wiki for future people to understand, still needs discussion.

### Goal
AssetData is a way to catalog every object, item, gas, icon, sound, and more, it helps us to write the code and automate everything, for example:
>  we need an icon for the "open" interaction, instead of referencing it on the **Item**, which is the way we do now, we reference it via code in the base interaction, so we don't need to do it for each item that has the open interaction.

The AssetData we want has to comport:
- Items
- Objects (in this case, every fixture, if possible, separate by category but we'll see)
- Sounds
- Icons
- VFX
- Entities

**BOUNTY: $100**

**Comment by joaoburatto** [comment]
Already being implemented
