### ISSUE TITLE
Add end of round mechanics

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#629]
### Summary

Add end of round mechanics.

### Goal 

Basically, a trigger to end the round for the players. Sends all players back to lobby.
I think it is tied to a timer currently, but adding a way to trigger it from in-game would be nice too, ~~like from a command console.~~
Currently decided to use a _nuke_ instead.

**BOUNTY: (RAISED TO) $45**

**Comment by joaoburatto** [comment]
if you want a console, please create an issue for it, we need that being designed if we want to implement it
