### ISSUE TITLE
Light leaks through walls

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#630]
### Summary

Light currently goes through walls which has obvious issues.

### Steps to Reproduce

- Go into the maintenance tunnel behind the bathrooms or library on the 'Main Station' map.
- Notice that these tunnels have no lights yet are illuminated by the adjacent rooms.

![image](https://user-images.githubusercontent.com/41941008/113048395-7d54b480-9170-11eb-8a1e-355803c7e7f5.png)

**Comment by Seteron** [comment]
Light only 'leaks' on Potato (the current default and Low quality mode, shadows are intentionally disabled on these modes currently for performance reasons. Not a Bug.
