### ISSUE TITLE
Rename Creature to Entity

### ISSUE THREAD

**Issue by joaoburatto** [RE-SS3D/SS3D#632]
### Summary

The term **Creature** is too restrictive and makes little sense in the context we are putting it in, so we gotta change it to **Entity**, which is common on other games and its easy to understand.
Marked as high priority cause we can't have more stuff built over it, renaming this already impacts like 8 files.

### Goal 

Rename the class **Creature** to **Entity**.
This will require changes on many other files that used the old term.

**Comment by DoomsdayOrange** [comment]
Jesus christ finally

**Comment by joaoburatto** [comment]
> Jesus christ finally

Sorry I created it with **Creature**, big mistake.

**Comment by DoomsdayOrange** [comment]
> > Jesus christ finally
> 
> Sorry I created it with **Creature**, big mistake.

I thought Eiko was the one who labeled them creatures

**Comment by cosmiccoincidence** [comment]
> > > Jesus christ finally
> > 
> > 
> > Sorry I created it with **Creature**, big mistake.
> 
> I thought Eiko was the one who labeled them creatures

That was just the folder name for them. Which it still is
