### ISSUE TITLE
Hidden and Implicit Containers

### ISSUE THREAD

**Issue by LightVelox** [RE-SS3D/SS3D#652]
### Summary

Right now all containers have interactions for them to be opened, we need Implicit and Hidden containers in cases like the Cell Charger where you just have to store one Power Cell, there is no need for any type of UI, that is a a Implicit Container.
We'll also need Hidden Containers, containers that have their initial items and that's it, you can never take them out or put others inside. And some way to to enable and disable item storaging in real time is needed too, for containers that can be locked and unlocked

### Goal 

Support for Machinery Storage(Batteries, etc), Lockers and Single-Slot Containers

**Comment by cosmiccoincidence** [comment]
**BOUNTY: $40**

**Comment by cosmiccoincidence** [comment]
Currently claimed and being worked on by LightVelox.
