### ISSUE TITLE
Add Non-Item Support to Container System

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#653]
### Summary

The container systems need added support for non-item objects like entities and furniture.

### Goal 

Some furniture objects are shipped in crates and such via cargo, also you can put entities in containers like lockers, crates, etc.

**Comment by cosmiccoincidence** [comment]
Maybe should wait on container rework.

**Comment by stilnat** [comment]
@cosmiccoincidence  I'm working on this one too, it'll be the second part of the container rework, can you assign me please ?
