### ISSUE TITLE
Item-Attachment-Point Gizmo Missing due to Missing Mesh Filters

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#656]
### Summary

It seems the gizmo for the item attachment point does not show up on some items and that it is a result of them missing the Mesh Filter script. Some items below that have this issue but ultimately all items should be checked over for this issue.

See:
- Uzi
- Enforcer
- Laser Cannon
- Energy Sword
(There are probably others but that should be a good starting point for you)

### Goal 

Fix please.

**Comment by cosmiccoincidence** [comment]
Eiko found the fix for this... It was due to the fact that these objects were missing the Mesh Filter.

I'll leave this issue open and rename it.

**Comment by cosmiccoincidence** [comment]
Alternatively, we can remove the mesh filter if we replace the current gizmo with another.

**Comment by EikoBiko** [comment]
[This](https://github.com/RE-SS3D/SS3D/pull/657) would fix it. :)
