### ISSUE TITLE
Ragdoll Documentation

### ISSUE THREAD

**Issue by onebigames** [RE-SS3D/SS3D#66]
**Description**
For each User Stories completed, a small guide on how to set up and use the feature should be made on Github Wikis

**User Story Link**
https://github.com/RE-SS3D/SS3D/issues/57
https://github.com/RE-SS3D/SS3D/issues/58
https://github.com/RE-SS3D/SS3D/issues/59
https://github.com/RE-SS3D/SS3D/issues/60

**Comment by TimFinucane** [comment]
We'll write up the documentation as part of the feature design work
