### ISSUE TITLE
Tie mobile container animations to inventory

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#668]
### Summary

The animations on mobile containers are currently tied to an open/close interaction which gives access to the inventory.

Mobile containers should NOT have the open/close interaction as this will become cumbersome in gameplay. So the open/close interaction should be removed and the animation should be tied to the inventory instead. 

So basically when you access the inventory the animation 'opens', and when the inventory closes (either by closing it manually or by walking away from it) the animation will 'close'.

Note: this only applies to medkits and toolboxes currently.

**Comment by cosmiccoincidence** [comment]
Note: this task was written as "mobile containers" but it should be "certain containers" as there are non-mobile containers that this will be relevant for as well (like the microwave).

**Comment by stilnat** [comment]
that should be part of PR #798
