### ISSUE TITLE
Can't play if join after Round Start

### ISSUE THREAD

**Issue by LightVelox** [RE-SS3D/SS3D#672]
### Summary

The player is incapable of entering the game if he joins after the map was already loaded by the Host, also, if he joins after the countdown, it will glitch and will start to count back up. the Join button stays darkened.

### Steps to Reproduce

1 - Open two instances of the game
2 - In one of them, host the game and load the map
3 - Join in with the client instance

To have the glitched countdown do this instead:
3 - Start the round and spawn on the Host Instance
4 - Join in with the client instance

### Expected Behavior

If a player enters the game after it already started he should load the map and be able to spawn.

### Possible Solution

Not really sure how to fix it completely, but apparently the problem is because when the map is loaded, it is loaded to all clients at the same time, maybe if the client can load it after joining in it might fix part of the problem.

### Media
![image](https://user-images.githubusercontent.com/28792244/119738259-cebeae80-be56-11eb-89f6-318829706dc2.png)

**Comment by cosmiccoincidence** [comment]
Happens to me too. Literally anytime you hit the 'start round' button on the hosted game prior to hitting the 'join' button on the main menu on the other.

![image](https://user-images.githubusercontent.com/41941008/120368924-a284b100-c2e0-11eb-8033-de10df963426.png)

![image](https://user-images.githubusercontent.com/41941008/120369134-dbbd2100-c2e0-11eb-84ad-cc1685397ced.png)

(Tested on game version 0.3.95c)

**Comment by henkhooft** [comment]
I took a look into the issue and it is related to how scenes are loaded and rounds are started. The message to load the selected scene is only send in the lobby once, so clients joining later will have missed it and Mirror will complain that it cannot find scene objects.

Also the RoundManager isn't properly communicating to clients that the round was started after joining. Which means that on the client you cannot use the Embark button even after loading the correct map.
