### ISSUE TITLE
Host closing game crashes everyone's computer

### ISSUE THREAD

**Issue by LightVelox** [RE-SS3D/SS3D#674]
### Summary

If the host loads the bigger map, both him and the client play around a bit and then he just closes the game's window instead of closing it from the menu, the client's computer will freeze

### Steps to Reproduce

1 - Open game on the bigger station map
2 - Play around a bit with both host and client, taking items in and out of containers, creating and deleting walls, etc...
3 - Go to the host's game window and close it directly with the "X" rather than from the menu(didn't test if it happens when using Alt + F4)

### Expected Behavior

It shouldn't freaking kill the client's computer

**Comment by EikoBiko** [comment]
holy shit lol

**Comment by cosmiccoincidence** [comment]
When I close my host it doesn't freeze my computer but it does freeze the client window.

Tested on 0.3.95c
