### ISSUE TITLE
Items stuck against walls on tables

### ISSUE THREAD

**Issue by Shillelagh-Hummus** [RE-SS3D/SS3D#681]
When throwing an object against a wall the wall collider allows the item to slip slightly past the grab distance, trapping it there until the table is removed. This could probably be fixed by expanding the wall collider a bit or making the table collider occupy the full tile.

**Comment by cosmiccoincidence** [comment]
Currently this bug does not exist in any of our builds and on the github, just in your WIP branch. For now Imma slap a 'blocked' label on this so people don't get confused when looking for it.
