### ISSUE TITLE
Add artwork to ID card examine interface

### ISSUE THREAD

**Issue by Ryan089** [RE-SS3D/SS3D#693]
### Summary

The ability to examine ID cards has now been implemented. This can be done by standing next to (or picking up) an ID card, holding down the Shift key and hovering the cursor over the ID. However, the interface is only a placeholder, and requires an artist to make it look more like an ID card and less like a computer error.

### Goal 

Make the ID card examine interface aesthetically pleasing.

### Media

The current placeholder art looks like this:

![ID bad](https://user-images.githubusercontent.com/64360820/121165121-611d7400-c893-11eb-8d03-166824402c6f.JPG)

It would be nicer if it looked something like this:

![ID good](https://user-images.githubusercontent.com/64360820/121165221-72ff1700-c893-11eb-9fcf-6a75b163c88b.JPG)
(All credit to Eiko!)

### Notes

- The prefab to amend is Content/Systems/Examine/UI/Identification Card.prefab
- The ID card will populate the details of one randomly selected character each time the game is loaded.
- You may (or may not) wish to change ID colours, style etc depending on which department the person works for
- If anything is going wrong programmatically when examining the ID, or you need different data fields programmed and can't work out how to do it yourself, contact Ryan on Discord.
- The actual portrait image of the person is out of scope for this task. That can be tackled at a later date.

**Comment by cosmiccoincidence** [comment]
There's a week before the end of the month, knowing how Eiko works I wouldn't be surprised if his IDs are WIP for a few months, so I think we should just use the example you posted on your description as a placeholder and get that in soon so it looks better for the monthly blog.
