### ISSUE TITLE
Make Targeting Doll Collapsible

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#694]
### Summary

I recommend putting a button (similar to the button used to collapse the clothing UI) in the bottom right corner and have it toggle the combat targeting doll.

To fit this button in,
- Move the targeting doll up,
- Add the toggle button in beneath it on the right
- Move the intent button beneath the targeting doll on the left
(see my crappy image)

Note: The UI may get changed or moved around again at a later date, but this is a nice small improvement for now.

### Media

![Untitled](https://user-images.githubusercontent.com/41941008/121244419-d6c21980-c86c-11eb-9747-ee2d21dad100.png)

**Comment by jamesblack3** [comment]
Hey I'll take this issue!
