### ISSUE TITLE
[Task] Custom Transform

### ISSUE THREAD

**Issue by TimFinucane** [RE-SS3D/SS3D#70]
Current NetworkTransform doesn't allow for teleportation, and so looks bad when on objects that e.g. need to be placed, as the component will attempt to interpolate between the two positions (and then give up and teleport anyway after too long a time).

Create or rewrite the NetworkTransform to allow teleportation. Could look at the original Unity NetworkTransform for inspiration, some options are:
- Apply teleportation when the new position is very far from the old one
- Have a public method that can be called to perform the teleportation

**Comment by onebigames** [comment]
Closing as https://github.com/RE-SS3D/SS3D/pull/71 fixed it
