### ISSUE TITLE
Add Container Name to Container UI

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#701]
### Summary

Title.

Nothing fancy need right now, we can always change and add to it later, but its nice to know what container UI I'm looking at when I have more than 1 open at a time.

### Media

Purple rectangle is prime real-estate.

![Unity_EsgovZx3Mx](https://user-images.githubusercontent.com/41941008/121634230-30376d80-ca52-11eb-8c17-f6462acb877f.png)

**Comment by stilnat** [comment]
I'm on it
