### ISSUE TITLE
Light Fixture Interactions are Broken

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#726]
## Summary

Seems light fixture on/off interactions have been broken due to recent file changes.

## Current Behavior

Can't click lights to turn them on/off anymore. The interaction option doesn't appear when right-clicking either.

## Context

*Experienced on version 0.3.95e*

Original implementation here: https://github.com/RE-SS3D/SS3D/pull/610

**Comment by Ryan089** [comment]
Part of this issue is that wall colliders have been increased in size, and therefore the Raycast is hitting the wall rather than the light. One way this could be resolved is resizing the wall collider for a closer fit.

**Comment by cosmiccoincidence** [comment]
Reducing the size of wall colliders will leave small gaps between the walls where items can glitch into, we had done something like this in the past.

**Comment by Ryan089** [comment]
The other option is to change the way the interaction system identifies what has been selected, rather than the current RaycastHit. I'm planning to look into this option later to see whether it's feasible, but I'm trying to focus on the 0.3.96 milestone first.
