### ISSUE TITLE
Posters Examine UI Goes Off-Screen

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#730]
## Summary

Posters when examined display a close-up UI, this UI is sometimes too high on the screen and goes off of the screen.

![ShareX_NMHRG8I9An](https://user-images.githubusercontent.com/41941008/124341469-a3805b00-db8a-11eb-9b08-aa6466f2ef2f.png)

*Experienced on version 0.3.95e*

**Comment by Ryan089** [comment]
As well as posters, this bug also affects the examine display for the identification card. Please resolve this issue concurrently. A good start point for this task is the RefreshDisplay() method of the UISimpleImage.cs and UIIdentificationCard.cs scripts.

**Comment by NazarDoeH** [comment]
I will take this issue.
