### ISSUE TITLE
Cant Examine Screwdrivers

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#731]
## Summary

Title.

https://user-images.githubusercontent.com/41941008/124341589-6a94b600-db8b-11eb-820c-b00f24dcdf11.mp4

**Comment by Ryan089** [comment]
Excellent first issue for a very junior programmer looking to begin contributing. If unsure how to do this, check out the "Making an object examinable" section of the [Examine system design document](https://drive.google.com/file/d/1xTyRXzi1g7H3SOkw1wkrFFbMcDUA0VEE/view?usp=sharing).
