### ISSUE TITLE
Re-Enable Chat

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#737]
## Summary

Enable the chat system.

## Goal 

John disabled the chat system many months back as it was just getting in the way of other things at the time and with no servers being hosted anywhere, there is no one currently to talk to...

Let's re-enable it so users can play with it and make suggestions, point out bugs, the usual... but let's ALSO make it collapsable like the clothing inventory UI (a button that toggles the chat open and close like in the image below). This way contributors can work on the chat system, but others can easily keep it out of their way.

## Media

![Untitled](https://user-images.githubusercontent.com/41941008/125014256-59402380-e03b-11eb-8ca9-2a365366e963.png)

**Comment by jamesblack3** [comment]
I could try and tackle this one.

**Comment by jamesblack3** [comment]
I'm having trouble finding where John disabled the chat system. Is there a PR where he does this?

**Comment by jamesblack3** [comment]
Nvm, figured it out
