### ISSUE TITLE
Clothing Containers

### ISSUE THREAD

**Issue by TimFinucane** [RE-SS3D/SS3D#74]
**Description**
Clothes may have containers on them, e.g. pockets, suit container slot, etc.

Containers on clothes must be accessible to the player. If on the player they should be accessible through the hotbar (for pockets) or body ui element (anything else). Yes, this means that multiple containers will appear in that element.

UI Slot Elements therefore need 3 states - not present (no container), present but holding nothing, and present and holding something. The appearance of these is to-be-discussed.

This task does NOT deal with looking at clothing containers on another body.

**Dependencies**
- This task is dependent on #73 
- Designs of the look of all possible pockets on the player's body UI element
- Appearance of item slots when there is no container for them (e.g. when player isn't wearing pants)

**Comment by cosmiccoincidence** [comment]
closed by #576
