### ISSUE TITLE
Simple Examine on Hover

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#747]
## Summary

Tweak examine system functionality so the simple examine feature is more akin to that of ss13.

## Goal 

Make the simple examine activate upon hovering your cursor over an object. The text should appear at the bottom of the screen, centered above the hand slots (see image). This only-hovering examine should NOT display the examine description.

Note: Do not remove the current method of activating the simple examine (<kbd>shift + hover</kbd>), this will remain as the method to get more detailed examining (like descriptions).

## Media

![ShareX_rSVHQTK3TA](https://user-images.githubusercontent.com/41941008/126570928-ccd6af23-36e3-465d-a0ae-fd9d95590afe.png)

**Comment by Ryan089** [comment]
How long do you need to hover over the item for the item name to show up at the bottom? Or do you want it to show up immediately?

**Comment by cosmiccoincidence** [comment]
Immediately.
