### ISSUE TITLE
Snack Machine has 2 Glass Panels

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#749]
## Summary

The snack machine seems to be displaying both of its glass panels (regular and broken).

## Goal 

Not sure why, the other vending machines with glass panels don't seem to have this issue from what I've seen.

## Media

![RESS3D_LUdAVIvV5B](https://user-images.githubusercontent.com/41941008/126576778-f5a0ec9c-28ff-4141-86d7-05354df468b6.png)

*Experienced on version 0.3.95e*

**Comment by jamesblack3** [comment]
I have also noticed other vending machines having this issue.
![image](https://user-images.githubusercontent.com/47376325/126882317-a0e7e704-a791-4a13-adf8-258e63b86312.png)

**Comment by jamesblack3** [comment]
The prefab has the glass turned off. But while in-game they seem to be turned on again.

**Comment by nalewis** [comment]
Looking into getting started contributing. Tried to reproduce this issue as my starting point. I was unable to reproduce the issue.

![image](https://user-images.githubusercontent.com/22083562/148479944-579621cc-3031-4715-a82b-4c49da40a56e.png)
![image](https://user-images.githubusercontent.com/22083562/148479966-ccad17de-b04c-478b-9276-e7da3507afeb.png)

**Comment by cosmiccoincidence** [comment]
Interesting. It is possible the bug has since been resolved.
