### ISSUE TITLE
Better Examine Text Visibility

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#750]
## Summary

Better Examine Text Visibility

## Goal 

Currently, when you examine something and text is displayed, the text is all white and when certain objects are behind this all white text, it can be difficult to read.

There are a few options I see we could go about solving this:
1. A black (or dark) outline around the text.
2. A dark highlight on the text.
3. A dark semi-transparent window behind the text.

If you consider another option, that can also be considered.

## Media

![ApplicationFrameHost_okOvvQcFUs](https://user-images.githubusercontent.com/41941008/126585585-1c1c8a1d-fb54-471a-a926-0d3252527376.png)

**Comment by Ryan089** [comment]
I find it hilarious that the text you chose to display was "ass table"!

On a more serious note, I'd be happy with either option 1 or 2, but I'd prefer not to go with option 3 because it means we'd have to constantly resize the window to fit, and I think it would look kind of tacky.

**Comment by cosmiccoincidence** [comment]
I agree I would prefer options 1 or 2 over option 3, mostly because option 3 would take up slightly more space and conceals more of the screen.
