### ISSUE TITLE
Inconsistent UI Spacing

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#751]
## Goal 

1. ~~The spacing between icons on the left side of the UI and the middle is consistent but the right side has a larger spacing size it seems. This was likely due to making the icons appear more centered beneath the targeting doll at one point. Now that the doll is collapsable and we have more buttons on the right side, they should match the space as the rest.~~

2. The margin on the left and right sides of the UI buttons is consistent but the margin on the bottom is larger. Let's decide on a margin size that looks good and is consistent on all sides.

## Media

![image](https://user-images.githubusercontent.com/41941008/126694450-40f04a97-e197-4933-8922-33eea4dff7bd.png)

*Experienced on version 0.3.95e*

**Comment by Ryan089** [comment]
Was this resolved by #804, or does the problem still exist?

**Comment by cosmiccoincidence** [comment]
> Was this resolved by #804, or does the problem still exist?

The first half has now been resolved, I updated the description.
