### ISSUE TITLE
Chat Send Controls Not Working

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#752]
## Summary

Cant send a chat message by hitting the 'send' button (the small arrow at the bottom right of the chat window). Instead, the user must use the <kbd>Enter</kbd> key.

Note: Using the <kbd>Enter</kbd> key on the numbpad also does not work, despite the numbers working. This should also be fixed.

https://user-images.githubusercontent.com/41941008/126696646-71dd57e6-50c3-45b0-86ae-91e04f81872c.mp4

*Experienced on version 0.3.95e*

**Comment by jamesblack3** [comment]
Oh, missed this one. Sorry! I fixed it in my upcoming PR.
