### ISSUE TITLE
Chat is too Large

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#753]
## Summary

The chat is fairly large and when you go to open a new tab, the window will go off the screen it is so large.

Comparing the size of the text in the chat to the examine text also indicates the chat is on the large size.

## Context

![image](https://user-images.githubusercontent.com/41941008/126697328-6feaeaa8-6212-453b-a4da-af4a6b892db1.png)

*Experienced on version 0.3.95e*

**Comment by jamesblack3** [comment]
I've rescaled and added the little animation that the internal clothing UI plays to the other two UI components too! It'll be in the upcoming PR.
