### ISSUE TITLE
Improve Chat Tab Buttons

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#754]
## Goal 

- [X] 1. The buttons to control the chat tabs could use an upgrade. Switching tabs works fine and so does making a new tab, but the close button seems to be broken. This button should close the active tab, if the active tab is the only tab in the window then it closes the whole window.

- [X] 2. Move the new tab button to the left side of the chat (see my shitty image below).

- [ ] 3. Add a new minimize button where the new tab button was located (see my shitty image below). This button should toggle the whole chat window close while preserving all the tabs. Reopening the chat window is done by clicking the chat button at the bottom of the screen still.

## Media

![Unity_7oi7LojhQq](https://user-images.githubusercontent.com/41941008/126700088-8dd5fe62-5cc5-44a9-a14f-34e4403ddc0f.png)

**Comment by jamesblack3** [comment]
Okay, the first two are completed. Let me know if you want the upcoming PR to have 3.

**Comment by cosmiccoincidence** [comment]
> Okay, the first two are completed. Let me know if you want the upcoming PR to have 3.

I'll let you decide if you want to tackle 3 in the same one or not. If not, I'll cross out 1 & 2 and keep the issue open for 3.

**Comment by jamesblack3** [comment]
> 
> 
> > Okay, the first two are completed. Let me know if you want the upcoming PR to have 3.
> 
> I'll let you decide if you want to tackle 3 in the same one or not. If not, I'll cross out 1 & 2 and keep the issue open for 3.

Okay, I could do it as a separate PR later then! Someone else could try it before I get to it then.
