### ISSUE TITLE
New Chat Tabs Display Wrong Channel

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#755]
## Summary

When you make a new tab in the chat but with a specific channel, it displays the wrong channel name in the corner.

## Steps to Reproduce

- Create a new tab with a unique name and channel,
- Notice the wrong channel name is displayed in the channel box,
- Try changing channels to the correct one (nothing happens),
- Try typing and sending a message and it appears the correct channel is active but not displaying in the corner.

https://user-images.githubusercontent.com/41941008/126701696-ff5fbbdb-704c-405a-8863-73ae3221b169.mp4

*Experienced on version 0.3.95e*

**Comment by jamesblack3** [comment]
I'm going to try this one out as it is related to #761's testing.
