### ISSUE TITLE
Allow Re-Ordering of Chat Tabs

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#756]
## Summary

Allow the user to re-order their chat tabs by dragging them around much like an internet browser. This would make the custom tab functionality a bit more user-friendly.

**Comment by jamesblack3** [comment]
This is the last one I could tackle for the PR.

**Comment by jamesblack3** [comment]
Okay, they can now be reordered! Going to draft up the PR now.
