### ISSUE TITLE
Multiple Chat Toggle Buttons

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#757]
## Summary

When splitting multiple chat tabs into separate windows, it seems to make a new copy of the chat window toggle button for every new chat window. This can be seen in the video below, watching the semi-transparent chat button, you will notice it get more and more opaque every time I create a new chat window.

## Solution

There should only ever be 1 chat toggle button, this button should be tied to all chat windows so it opens/closes all chat windows (obviously keeping their tabs saved as well).

## Context

https://user-images.githubusercontent.com/41941008/126703787-40dbccad-0d5a-47d2-be1f-bd1a318d655c.mp4

*Experienced on version 0.3.95e*

**Comment by jamesblack3** [comment]
I'm responsible for this one because I didn't know our chat could be split like that! I can fix this by moving the chat button to the InventoryUI prefab instead of the ChatWindow prefab.

**Comment by cosmiccoincidence** [comment]
> I'm responsible for this bug because I didn't know our chat could be split like that! I can fix this by moving the chat button to the InventoryUI prefab instead of the ChatWindow prefab.

No worries, I didn't notice the bug during my initial testing so it's on both of us. That would be great if you would like to fix it. I'll assign you to it.
