### ISSUE TITLE
Walking/Interacting while Typing

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#758]
## Summary

Your character will move or even interact while you are typing in the chat. This should be prevented.

## Steps to Reproduce

- Pick up an item then select the chat box,
- type <kbd>w</kbd>, <kbd>a</kbd>, <kbd>s</kbd>, or <kbd>d</kbd> and your character will move despite you typing in the chat box,
- type <kbd>q</kbd> and your character will drop what they were holding.

I presume this happens with other key-based interactions as well.

*Experienced on version 0.3.95e*

**Comment by jamesblack3** [comment]
I'll try this one. I am having trouble reproducing it, but I have done it before too.

**Comment by jamesblack3** [comment]
Oh I did find a new bug though. While moving, click on the text box. Your character will stop moving, but will still animate as if he is. You can type as normal otherwise.

**Comment by jamesblack3** [comment]
Another bug. The ">" button right next to the chat box which should send the message does nothing.

**Comment by cosmiccoincidence** [comment]
> Oh I did find a new bug though. While moving, click on the text box. Your character will stop moving, but will still animate as if he is. You can type as normal otherwise.

I haven't seen this one yet. Care to record a clip and submit an issue detailing this bug?

**Comment by cosmiccoincidence** [comment]
> Another bug. The ">" button right next to the chat box which should send the message does nothing.
> EDIT: That was an easy fix, will include in my PR

This bug is detailed on #752

**Comment by jamesblack3** [comment]
I'll try this issue out. It has to do with not checking the focus first.

**Comment by jamesblack3** [comment]
Okay, got this one figured out. It'll be in the upcoming PR!
