### ISSUE TITLE
Weird Ghost Chat Window

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#759]
## Current Behavior

You can drag the last chat tab out of a chat window leaving behind a weird ghost chat that still behaves like the last tab that was in it but does not display the actual chat log.

## Steps to Reproduce

- Not sure if it works on the original tab but I made a 2nd tab then separated it,
- Then separated that tab from its window as well despite there being no other tabs in that window.

## Possible Solution

Do not allow the user to separate the last tab from a chat window.

## Context

https://user-images.githubusercontent.com/41941008/126706133-b6d1236c-9c2b-4ca9-9fd7-09feba7e59f1.mp4

*Experienced on version 0.3.95e*

**Comment by jamesblack3** [comment]
I've started on this one. I can get it to not create new chat windows, but I've noticed if you have two chat windows and you merge one tab into the other, then the old chat windows is still there with no tab, haha! I think this could be related enough to be fixed in this issue as well.

**Comment by jamesblack3** [comment]
This one is solved and will be in the upcoming PR.
