### ISSUE TITLE
Default Chat size is smaller than minimum size

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#760]
## Summary

The default size for the chat window is smaller than the minimum allowed size when scaling it. This means that the moment when you scale the UI is 'snaps' to a large size (the minimum size) and there is no way to reduce the size back down as small as to how it started.

## Steps to Reproduce

Try to scale the chat window.

## Possible Solution

The minimum scalable size should be changed to match the default size.

## Context

https://user-images.githubusercontent.com/41941008/126706979-e9f4581b-7b35-4c16-b988-fb178552f540.mp4

*Experienced on version 0.3.95e*

**Comment by jamesblack3** [comment]
Think this got fixed while I was addressing #753. However the chat resizing looks very wrong. Is there an issue for that?

**Comment by cosmiccoincidence** [comment]
> Think this got fixed while I was addressing #753. However the chat resizing looks very wrong. Is there an issue for that?

Can you elaborate on the issue? But I don't think there is. 

You can quickly access all chat related tasks by using the "System: Chat" label.

**Comment by jamesblack3** [comment]
Okay, fixed the chat resizing. It'll be in the upcoming PR.

**Comment by Ryan089** [comment]
Is this still an issue, or was it fixed in #779? I cannot replicate it in 0.3.95g.

**Comment by cosmiccoincidence** [comment]
> Is this still an issue, or was it fixed in #779? I cannot replicate it in 0.3.95g.

Good catch. This got resolved already.
