### ISSUE TITLE
Can't Tell Selected Chat Tab

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#761]
## Summary

There is no indication of which tab in the chat window is currently active.

![image](https://user-images.githubusercontent.com/41941008/126717692-f4d852ae-3512-4a4b-99a0-deff565dc3ba.png)

 ## Solution 
 
 Darken the selected tab.

*Experienced on version 0.3.95e*

**Comment by jamesblack3** [comment]
I'd like to try this one out!

**Comment by jamesblack3** [comment]
Okay, it'll be in the upcoming PR!
