### ISSUE TITLE
Chat is 'hackable'

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#762]
## Summary

You can hack the chat by customizing your text (and probably other things).

## Steps to Reproduce

Use `<size=70>Message` or `<color=blue>Message` and you will notice you can customize you text. I haven't tested this across multiple clients but I'm guessing it comes across the server like this too. The user should not be able to customize their chat text like this (later one when we get writing this will be possible in that system though).

![image](https://user-images.githubusercontent.com/41941008/126718225-56e855c2-088e-4913-94e7-6a9390402c3a.png)

*Experienced on version 0.3.95e*

**Comment by jamesblack3** [comment]
I could take a look at this one. Probably some setting within TextMeshPro.

**Comment by jamesblack3** [comment]
Okay, as I suggested, just a setting that needed adjusting. Also needed to add <noparse> to what users send.
