### ISSUE TITLE
Space Cleaner Continuously Spraying

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#768]
## Summary

The space cleaner bottle just keeps spraying every 10 seconds or so, non-stop.

## Steps to Reproduce

- Load a map with a space cleaner bottle and playtest it.
- Go view the space cleaner bottle in-game.

IIRC the spray bottle was set up similar to the pepperspray and although neither seem to have an actual interaction to toggle the spray, I do not see the bug on the pepperspray.

## Context

Experienced on version 0.3.95e

**Comment by jamesblack3** [comment]
Sounds like a janitor prank. I could take this one

**Comment by jamesblack3** [comment]
Interaction is F. The particle system specifically for the space cleaner was set to loop, which caused it to spray every few seconds.
