### ISSUE TITLE
Implement new movement animations

### ISSUE THREAD

**Issue by DoomsdayOrange** [RE-SS3D/SS3D#77]
[Outdated. Please message mention me on Discord @Probably Not for up-to-date animations.](https://cdn.discordapp.com/attachments/603622883075293214/640748667883749426/Character_Default_Movement_WIP.zip)

Included is 

- the default idle pose (No idle animation Yet
- Walk from idle and back to idle
- Walk forwards/sideways/backwards/diagonal/backwards diagonal
- Run forwards/sideways/diagonal

**Comment by Dyhr** [comment]
How will this work with the control scheme? 
Right now we only know that we need idle, walk, and run and only in the forwards direction.
Are the walk and transition animations synced so we can easily interpolate between them?

**Comment by Dyhr** [comment]
![image](https://user-images.githubusercontent.com/172592/72531375-988c1a80-3871-11ea-956b-c9129032bb4a.png)
You animations are all named "Take 001", making them hard to distinquish

**Comment by Dyhr** [comment]
The walk and run animations do not blend well

**Comment by cosmiccoincidence** [comment]
Animations that still need to be implemented for this are:
- turning
- walking sideways
- walking diagonally
- walking backwards
- from/back to idles

If you need help with this issue, talk to @Probably Not on the Discord.
