### ISSUE TITLE
Toggle Chat with "c" key

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#774]
## Summary

Toggle ALL chat windows with the "c" key.

The chat UI button already does this, so I suggest checking it out.

**Comment by jamesblack3** [comment]
Okay, C now works to open and close all chat windows. Even added a Toggle Chat listing in the controls. It'll be in the upcoming PR.

**Comment by jamesblack3** [comment]
Found a bug with this one. Might be related to #758 but I can close the chat window while typing with a C.

**Comment by cosmiccoincidence** [comment]
> Found a bug with this one. Might be related to #758 but I can close the chat window while typing with a C.
> EDIT: Okay, fixed this one.

Maybe CRTL + C could be used to close it.
