### ISSUE TITLE
Duplicate Audio Listeners in Multiplayer When Midround Joining

### ISSUE THREAD

**Issue by calmilamsy** [RE-SS3D/SS3D#795]
## Summary

The player prefab is recycled for multiplayer characters too, and it contains an AudioListener, which there should only ever be one of in a scene.

## Current Behavior

Unity will flood the console with 999+ errors, and you will also hear double audio, unless the Unity sound system breaks first.
Also creates a ton of lag as it logs these errors to the editor console.

## Steps to Reproduce

1. Host a server on another client.
2. Start the round.
3. Use the editor to join.
4. Watch unity count 999+ errors about double audio listeners.

## Expected Behavior

There should not be another audio listener created when another player joins.

## Possible Solution

Remove the audio listener from the player prefab, and instead attach it to the camera. This would also likely make directional audio come from the camera's perspective instead of the player.
OR
Create a second player prefab to use for other player, which will keep existing audio behaviour, and *might* make multiplayer interactions a little easier to do.

![image](https://user-images.githubusercontent.com/8781747/131225931-508614df-70cc-406e-872c-fc039d6342b3.png)

## Context

This is recreatable on the latest commit (cff1166).
Tested using Unity 2019.3.12f1 and 2019.4.29f1.

**Comment by Ryan089** [comment]
I was unable to reproduce the fault. Were you getting the errors on the client or the server?

**Comment by calmilamsy** [comment]
Client, server does not have this issue for some reason.

**Comment by Ryan089** [comment]
From the look of the screenshot, it looks like you may not be using the Unity version that the project uses. Which version are you on?

**Comment by calmilamsy** [comment]
Version 29f, but it also happened o  the supported version before I updated too.

**Comment by calmilamsy** [comment]
Okay, found the exact way to replicate. Main post has been updated.
