### ISSUE TITLE
Custom Container UI

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#809]
## Summary

Some containers could have a special UI, the ID console was mentioned in particular. The basic container interactions should be preserved by the UI. As a suggestion, it could be a background picture with the slots of the containers positionned freely on the picture.

## Goal 

The goal is to allow players to quickly understand what they have to do through the UI, which is not possible with a basic
containerUI in some case.

## Dependencies

This should wait until #683 is closed.

**Comment by Birlinha** [comment]
Why have Container interfaces at all?

I mean - I am a great fan of Resident Evil. Managing 2D spaced inventories has always been one of my favorite things

But the game is 3 dimensional now - The interface of the container could be the container itself (the toolbox in this case)
We could click with a mouse on a tool inside a toolbox, or use a VR controller to quickly point to what we need

Maybe we could able both? Being able to manage a 2D inventory, which is inside a 3D container, and you could select your tool from both of them

**Comment by Birlinha** [comment]
But for this specific Issue #809, I believe a possible solution would be to use HTML styling, just like you can use < /noparse> in chat to style your text, like mentioned in issue #806

Something like this: 
[htmltoolbox.zip](https://github.com/RE-SS3D/SS3D/files/7148595/htmltoolbox.zip)


But making the toolbox HTML-like might create a lot of concerns (just like in issue #806) - for example: Will it be possible to use <script> tags?

**Comment by stilnat** [comment]
> 
> 
> Why have Container interfaces at all?
> 
> I mean - I am a great fan of Resident Evil. Managing 2D spaced inventories has always been one of my favorite things
> 
> But the game is 3 dimensional now - The interface of the container could be the container itself (the toolbox in this case)
> We could click with a mouse on a tool inside a toolbox, or use a VR controller to quickly point to what we need
> 
> Maybe we could able both? Being able to manage a 2D inventory, which is inside a 3D container, and you could select your tool from both of them
> 
> Just found [an issue that describes showing the object inside the 3D object -#803-](https://github.com/RE-SS3D/SS3D/issues/803)

User interfaces showing inventories inside an object are common in 3d games for the reason that it's easier to manage for the player. It also create a mechanics for storage capacity, among other things. Having no user interface could turn into a nightmare, if you just want to retrieve some small items in a container but first you have to move around everything. They're pretty essential for a smooth experience .
