### ISSUE TITLE
Allow examine system hover text to be toggled 

### ISSUE THREAD

**Issue by Ryan089** [RE-SS3D/SS3D#811]
## Summary

Currently examine hover text identifies the name of the item that the mouse is hovering over. The behaviour of this hover text should be able to be toggled by the user to suit their preference.

## Goal 
- [ ] Create toggle in Graphics Options menu for "Display item name under cursor" (or similar), with options:
    - Always
    - Delayed
    - Never
- [x] Implement "Always" option - whenever cursor is over an examinable item, the item name is displayed at the base of the screen. Note: the hover text is not shown when the user is holding down shift, as they are conducting a more detailed examination and the details will appear closer to the cursor.
- [ ] Implement "Delayed" option - whenever the cursor has been stationary over the same object for at least one second, the item name is displayed at the base of the screen. If the user moves the cursor or if the item under the cursor changes, the name is hidden again and the timer reset. Again, the hover text will disappear if you are holding down shift.
- [ ] Implement "Never" option - the item name is never displayed. Note: the user can still conduct the detailed examination by holding down shift and hovering over the item.

## Media

![Hover Text](https://user-images.githubusercontent.com/64360820/133388296-0416bced-67b5-4a13-8d3d-05921e7bbb5e.png)
**Image 1:** Example of hover text

![Graphics options](https://user-images.githubusercontent.com/64360820/133388540-8c6f56f7-c04a-41cb-abd0-d92392670e50.JPG)
**Image 2:** Current graphics option page. Toggle settings should go here.

## Document

Examine system design document is [here](https://docs.google.com/document/d/1xTyRXzi1g7H3SOkw1wkrFFbMcDUA0VEE/edit?rtpof=true).

#### Questions?
Ask Ryan on Discord.

**Comment by cosmiccoincidence** [comment]
> Implement mechanism to save individual player preferences, so that it persists between games.

Maybe this should be split off into another issue?

**Comment by Ryan089** [comment]
Sure. I've removed it from the issue.
