### ISSUE TITLE
Alternate Container: Dolly

### ISSUE THREAD

**Issue by LittleKachowski** [RE-SS3D/SS3D#813]
## Summary
The dolly (alternatively called cart or pallet) would be a pullable and pushable cart that allows players to scoop up loose items on the floor and move them en masse. This would function _identically_ to current SS13 lockers, although they will look and feel very different. Simply pull or push the cart underneath any loose and unbolted item or player, interact with the cart itself, and it will lock all items on top of it, tying it to the cart's model until unlocked. Any player that is locked to a cart can resist and exit it at will. Carts can be emagged or hacked to have their safeties removed, preventing people from fleeing a cart while allowing extra weight to be carried. A player in a hacked dolly would need to resist to escape similar to escaping cuffs.

The cart itself would look like a normal pallet dolly, however instead of forklift prongs it's a platform slightly smaller than a full tile. The platform would be as low to the ground as possible without touching it. The edges of the platform would be rounded and could possibly have a pattern on top to make it stand out from normal floor tiles. There would be a waist-height handle attached to the cart so we dont have to animate the player bending down to the ground pull/pushing it.

The platform of the cart would **_have no collision with entities_**. This would simulate the feeling of scooping up items off the floor and saving us time with the actual physics. If the cart's platform is low enough to the ground, this should look perfectly fine.

These dollies could be strewn around departments of the station (mostly cargo), along with a few in civilian storage sites. Perhaps there could be a couple heavy duty dollies with extra carry capacity and the ability to harmlessly trap living things in it. When THESE dollies are hacked, not only would they carry infinite weight, but maybe they could cause catastrophic damage to living things (excessive G-force strain on the body)

I'm unsure if these dollies should be constructible or require ordering. We can discuss this.
## Goal 
At the time of writing, people in the discord are having headaches trying to figure out how to reproduce SS13's locker systems with three dimensional lockers. Among them is the ability to drag a locker over a stack of XYZ and scoop it up for transport. This is largely undoable with the way lockers are going to store things and only one way for things to enter. The dolly would allow us to completely forget about this issue and allow real lockers to be programmed their own way. We wouldn't have to butcher our lockers for the sake of authenticity.

Dollies would be familiar to veteran players, as they would give players the ability to do the same things with dollies as they can with SS13's lockers. For example, botany delivering massive amounts of product, security scooping up evidence, and dragging large amounts of corpses at once. To a veteran player, dollies would act as a way to transport objects while lockers would act as purely a way to store things. **_This is not to say that lockers cant be dragged around with stuff inside, it just wouldnt be as simple as the scoop and dump method._**

Since dollies are uncovered, it would make it more difficult to smuggle a corpse or other stuff without people knowing whats on the dolly. And since you'll still have the option of lockers, it would create this interesting decision for people with bad intentions. Do you take the faster, uncovered dolly or the slower, clunkier locker with a door and a lock?

I wouldn't normally say something like this, but I STRONGLY recommend the dolly as a mechanic, because we're not going to be able to remake SS13's lockers 1:1, and players are going to want a way to dump items onto something and move it. Forcing players to individually file items into and out of a locker is going to be divisive to say the least.
## Context
![dolly](https://user-images.githubusercontent.com/90806939/133540985-c681760d-2e22-46bb-a258-ab5d9dfedfd1.png)

A real life form of what I'm talking about. For SS3D, the platform should be MUCH MUCH closer to the ground and very thin to allow _maximum scoopage_.

For the lore explanation of how a device works, I elect to call it a "Gravity Dolly" or "Quantum Cart", which would create a gravity field that forces objects to stay in place relative to the cart. Alternatively, we could explain it as quantum entangling. The cart's platform could have some kind of subtle animation or effect to convey that it's on. Maybe it'll be a different color to show it's hacked.

The cart could possibly float over the floor instead of roll on wheels as a result of magnetic levitation. This would explain how it's so close to the ground and how it can pick up so many objects for the platform's thickness.

**Comment by Ryan089** [comment]
I think this is a great idea. @DoomsdayOrange, do we have any models for something like this? If not, could you please raise a task for one? It's not a high priority, but if any programmers want to give it a go it'd be good to have the assets ready for them.
