### ISSUE TITLE
Performance optimization of Examine system

### ISSUE THREAD

**Issue by Ryan089** [RE-SS3D/SS3D#821]
## Summary

The Examine system uses a shader based method to identify examinable objects under the cursor, as described in the CompositeItemSelector section of the [Examine System Design Document](https://docs.google.com/document/d/1xTyRXzi1g7H3SOkw1wkrFFbMcDUA0VEE/edit#heading=h.rtygdkrf5487). This has always had a minor performance penalty when examining. However, two recent changes to the game have made this penalty significantly more severe:

- **Tilemap rework**. The Examine system was designed for the old structure, where individual tiles and their subordinate components (plenums, pipes, turfs etc) could be readily identified. This allowed only those specific objects to be re-rendered for the CompositeItemSelector. The new system does not provide the same ability to identify objects on the same tile, so currently the *entire* tilemap needs to be frequently re-rendered for the CompositeItemSelector.

- **Hover Text**. The Examine system now displays the name of the item under the cursor all the time. Because of this the performance penalty is also permanent, rather than only when the user is holding down the Shift key to examine something.

The combination of these factors mean that there is now a **major penalty all of the time**, whereas we previously had a minor penalty some of the time.

## Goal 

Dramatically increase the performance of the Examine system.

## Media

![NormalCamera](https://user-images.githubusercontent.com/64360820/134770145-57e33c14-6cd2-45df-a1aa-49239ff9bb46.png)![CompositeItemSelector](https://user-images.githubusercontent.com/64360820/134770150-412e570b-4496-484b-b3c0-82ee3cb73926.png)
CompositeItemSelector rendering part of tilemap under old system. It now renders entire tilemap.

![Profiler Examine System](https://user-images.githubusercontent.com/64360820/134770092-d6ce2390-93da-4f05-9c5b-b560b23aae33.JPG)
Profiler showing processing spikes caused by the Examine system.

![Profiler Composite Item Selector](https://user-images.githubusercontent.com/64360820/134770098-20675f6a-b282-4299-b194-0b4fa6e1a03e.JPG)
Frame showing that the CompositeItemSelector is responsible for ~75% of processing time during a spike (144ms in this frame). 

## Need more info?

Ask Ryan on Discord.

**Comment by stilnat** [comment]
I noticed those spikes too and was going to report them, even though I did not know it was due to the examine system. Good catch !
