### ISSUE TITLE
Implement Adjacency Connections for Counters

### ISSUE THREAD

**Issue by Ryan089** [RE-SS3D/SS3D#845]
## Summary

Like other connectables, counters are able to connect to form a coherent monolithic structure as described in the "Counter Adjacency Connections" section of the [Connectables Design Document](https://docs.google.com/document/d/1ful7_gIJo7e74i9LMQuYMpjZMH2V1aT90mwlrQ0hcgE/edit?usp=sharing). Implement the adjacency connector script to enable this. See MultiAdjacencyConnector.cs and IAdjacencyConnector.cs as a start point.
 
## Goal 

Counters can be placed in the Tilemap editor, with the appropriate mesh being selected automatically to form the appropriate shape based on the adjacent tiles.

## Dependencies

Assets required for this task will be added via #796.

**Comment by Notterox** [comment]
Hi, @Ryan089, assign me, please.

**Comment by Em3rgencyLT** [comment]
Depends on #865
