### ISSUE TITLE
Implement Directional Adjacency Connections

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#847]
## Summary

Implement a new tilemap adjacency connection script (similar to the others) for "directional connections". This should follow the design located in the link below.

## Goal

This will allow for modular seats and similar connectables to be added to the map via the editor and perform intended connections.

https://docs.google.com/document/d/1ful7_gIJo7e74i9LMQuYMpjZMH2V1aT90mwlrQ0hcgE/#heading=h.w1e4ju9ibvx6

**Comment by Em3rgencyLT** [comment]
Depends on #865
