### ISSUE TITLE
Implement Disposal Adjacency Connections

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#848]
## Summary

Implement a new tilemap adjacency connection script (similar to the others) for "disposal connections". This should follow the design located in the link below.

## Goal

This will allow for disposal pipes and their related machinery to be added to the map via the editor and perform intended connections.

https://docs.google.com/document/d/1ful7_gIJo7e74i9LMQuYMpjZMH2V1aT90mwlrQ0hcgE/#heading=h.76te83dxx76h

**Comment by Em3rgencyLT** [comment]
Is blocked by #865
