### ISSUE TITLE
Implement Window Adjacency Connections

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#850]
## Summary

Basically we have some complex connections for walls/windows/etc. and instead of modeling specific wall-window transitions as a whole piece, we have done so as a separate piece (called Window Dividers) that overlays that gap.

![dddd](https://user-images.githubusercontent.com/41941008/146283081-8a8acf71-1807-448d-ac41-353a904bde58.png)

Implement a new tilemap adjacency connection script (similar to the others) for "window connections". This should follow their design located [here](https://docs.google.com/document/d/1ful7_gIJo7e74i9LMQuYMpjZMH2V1aT90mwlrQ0hcgE/#heading=h.6mdz7btrako6).

This will allow for windows to be added to the map via the editor and perform intended connections.

The dividers should be a component on the window prefabs, and based on the shape of the window and its connections it may require multiple dividers.

[Window Connections](https://drive.google.com/file/d/1xxApzp_HZMPjx673J-fnwjSycuQCs614/view?usp=sharing)

[Model Guide](https://docs.google.com/spreadsheets/d/1pIAexmqe9es5v31bHQ2yVlyYP9tpQ1EO-1a9AVqU-dw/edit#gid=0)

## Context

Another connection script as example: https://github.com/RE-SS3D/SS3D/blob/master/Assets/Engine/Tile/TileRework/Connections/AdjacencyTypes/AdvancedAdjacency.cs

**Comment by Em3rgencyLT** [comment]
This depends on #865
