### ISSUE TITLE
Duplicate Door Frames

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#851]
## Summary

The tilemap seems to be generating double the amount of door frames as intended.

## Current Behavior

Clicking on a door (airlock) in the editor and viewing its child objects you will notice that there are 4 door frames (wall caps) instead of just the required 2.

![Unity_h91nG7qndY](https://user-images.githubusercontent.com/41941008/144766364-803bc56b-8f87-4384-a35d-c8558d816b1e.png)

Remapping the doors *seems* to fix this issue initially, but doesn't actually. If you try to remove the current doors and remap them it will indeed only add 2 door frames as intended, but when you save and close the map/project and then re-open it, there will be 4 door frames again.

## Possible Solution

Check "Door.cs" in /Assets/Content/Structures/Doors/ as this is where the door frames are handled. But the bug may have to do with the map saving system, idk.

**Comment by EikoBiko** [comment]
This is caused by the airlocks not checking to see if the door frames already exist before placing them, which apparently occurs in play mode. Every time you enter play mode, it generates two more.
