### ISSUE TITLE
Update AdjacencyBitmap.cs to remove methods returning connection types

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#864]
## Summary

With new adjacency connector scripts coming soon, we need AdjacencyBitmap.cs to be universal. It's currently supporting a few methods that are not adapted for all kind of connectors, making the code confusing and messy. 
Those methods should be removed, and the scripts using them consequently updated.

![image](https://user-images.githubusercontent.com/14344825/146682717-59ee08b7-61be-4e62-ad56-7e2e94110e08.png)

## Goal 

Remove the methods in the picture above. Update consequently the three scripts using them.
simpleAdjacency, AdvancedAdjacency, offsetAdjacency.

**Comment by stilnat** [comment]
@Em3rgencyLT type a comment so I can assign you

**Comment by Em3rgencyLT** [comment]
Assign me please
