### ISSUE TITLE
Diagonal lookup support for tilemaps

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#865]
## Summary

The current Adjacency Bitmap class allows to do a lookup for adjacencies in four directions. North, East, South and West. 
We need to expand this to do lookups for any of the eight directions, including the four mentionned and North-East, South-East, South-West, North-West.

## Goal 

Modify AdjacencyBitmap.cs so that the cardinalInfo struct contains information on the eight directions.
Modify the relevant methods returning information on them, GetOnlyPositive(), GetOnlyNegative(), maybe GetCornerDirection().
Make sure that modifying those methods doesn't break the scripts depending on them, simpleAdjacency, AdvancedAdjacency, offsetAdjacency.

## Dependencies

We should first cleanup the code and remove some methods, check #864 .
We might have to remove orientation enums first too #866

**Comment by Em3rgencyLT** [comment]
assign me
