### ISSUE TITLE
Add a simple ambient noise

### ISSUE THREAD

**Issue by joaoburatto** [RE-SS3D/SS3D#886]
## Summary

Add a simple background noise based on SS13's sound design or sound assets, mainly just white or brown noise. 

## Goal 

Making the station feel more empty, bringing back that really weird feeling of hearing the SS13 ambient noises when everyone died.

**Comment by Shillelagh-Hummus** [comment]
I'll give it a shot.
Maybe I can stick a microphone in my networking closet for a good ambience sound
