### ISSUE TITLE
Possible chat improvements

### ISSUE THREAD

**Issue by Em3rgencyLT** [RE-SS3D/SS3D#90]
Current chat implementation is simplistic and still lacking many main SS13 features. Raising this issue to make it is not forgotten and that it is visible to anyone who wants to contribute, as a lot of these changes are beginner level problems.

- No System channel (for server wide announcements, or NanoTransen messages). 
_System channel should not be accessible to players. But it should be possible to send messages directly to this channel from code and it should propagate over the network to all players._
- No Local chat, no OOC chat, no whispering, no private messaging, no emotes
_OOC chat is a simple global channel. Local chat and whispers should only be visible to nearby players (different range for each channel). Private messages would probably require a PDA to be present (needs discussing). Emotes should appear in a different style/font and only visible to nearby players._
- Everyone has access to all channels
_What channels you can receive/send to should depend on your headset (not implemented as of 2020-01-10) and what channels that headset has access to. Channels like Local, whisper or OOC are always accessible._
- Chat window position/size and tab setup is not persisted between game restarts
- It is impossible to tell which tab is currently selected
- Chat can be "hacked"
_Should prevent rich text formatting in the chat window by players. Should still be possible for System messages._
![Hackerman](https://i.imgur.com/Rb5VUQv.png)

**Comment by TimFinucane** [comment]
We should probably split a few of these into separate issues:
- tab selection
- rich text rules (first we need to figure out what the player *can* do, and how), emotes
- local channel
- private messages with PDA
- system and ooc channels

More also might come soon. I'll leave this open for now to get your opinion but if you agree we can close this and open new issues instead.

Additionally, we haven't yet written up a full design document for the chat feature so there might be some things that need to change in the future.

**Comment by Em3rgencyLT** [comment]
I absolutely agree that it needs to be split up. I just didn't want to spam the issues section. This issue should turn into a bunch of task/bug cards in the projects section and the issue should then be closed.

**Comment by cosmiccoincidence** [comment]
Split this issue into 4 separate ones, #761 #762 #763 #764 
Closing this.
