### ISSUE TITLE
Command Console - Basic functionality

### ISSUE THREAD

**Issue by joaoburatto** [RE-SS3D/SS3D#917]
## Summary

Implement a basic command console in the top of the screen that can process commands. Disclaimer: I have no idea what's the best architecture on doing this.

## Goal 

Make possible to send debug commands, as well as receiving text results from the application.

## Acceptance Criteria 

- [ ] Pressing the F12 opens the command console.
- [ ] The user is able to input text.
- [ ] The user is able to press the up arrow key to input their last command.
- [ ] The user is able to write "quit" to close the application.
- [ ] The user is able to write "reconnect" to restart the application (load the main menu again).
- [ ] The user can write **"changeperms"  + ckey + role** to change a user's permission.
- [ ] Pressing ESC closes the command console.
- [ ] The user can write "playerlist" to see the connected player list.
- [ ] The user can write "soullist" to see all the instantiated souls.
- [ ] Certain commands have a response that the application will display in the command console

**Comment by Dennis-Nesterenko** [comment]
I haven't read up on the docs but wouldnt soul and player be the same

**Comment by joaoburatto** [comment]
> I haven't read up on the docs but wouldnt soul and player be the same

Souls are persistent even if player disconnects, player is only those who are connected to the server at the moment

**Comment by etroo44** [comment]
Hello, can I work on this? Please assign me if I can. @joaoburatto

**Comment by iamteapot422** [comment]
Wouldn't it be better to open and close on the same key?
