### ISSUE TITLE
Hands and Inventory UI

### ISSUE THREAD

**Issue by TaylorNAlbarnaz** [RE-SS3D/SS3D#939]
## Summary

The game currently already has items and interactions, but the problem is that there is no UI related to that, meaning you can't see what items you have picked up, also preventing us from working on features like crafting and item-to-item interactions, you can just read how it was done in the "outdated" branch and replicate it, doing some small adaptations to the new systems.

## Goal 

- [ ] Having a UI for Hands
- [ ] Seeing which items you are currently holding
- [ ] Knowing which hand is the currently active one
- [ ] Optional: UI for the rest of the rest of the inventory(Pockets, Backpack, etc)

**Comment by stilnat** [comment]
Working on it
