### ISSUE TITLE
Add a Stamina System

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#949]
## Summary

[Following the health/medical design document](https://docs.google.com/document/d/1DnpwresKmUe3hDzDFpGI7o2iU4xUKfkx6gVieuP5pVM/edit#), implement the stamina subsystem, focusing on the running action as a source of stamina depletion. 

When the player stop doing actions depleting stamina, slowly refill the stamina. 

I think an independent script is welcome for it, maybe even create a new folder for the medical system and add the stamina script in it.

The stamina system should contain at least : 
- The current stamina value, always above 0.
- The maximum amount of stamina, can be changed during the game.
- The speed of stamina regeneration,  can be changed during the game.

When stamina is depleted, the running action should be prevented as long as stamina is 0.

Having a little bar showing stamina value would be a nice extra for debugging and visualising stamina. 

 

https://docs.google.com/document/d/1DnpwresKmUe3hDzDFpGI7o2iU4xUKfkx6gVieuP5pVM/edit#heading=h.apft046zl2hw

**Comment by Ryan089** [comment]
Thanks, I'll take this one.
