### ISSUE TITLE
Client unable to ready for new round after another round ends

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#962]
## Current Behavior

After a round ends, either by blowing the nuke or an admin ending it, the joining clients seem to be unable to ready up for the next round. The issue doesn't seem present for the host.

Notice the ready up buttons in the image below.

![SS3D_RsZyeGwoGU](https://user-images.githubusercontent.com/41941008/211220713-164a47e9-978b-4e41-a798-962413abd3a3.png)

## Replicate Bug

1. Open a host and a client window.
2. Ready up on both and launch the round from the host.
3. End the round via admin button or using the nuke disk in the nuke.
4. Make sure both the host and client screens revert to the server lobby.
5. See if the Ready Up button is selectable on the client window.

**Comment by joaoburatto** [comment]
Could not replicate

**Comment by cosmiccoincidence** [comment]
I should add that in my test I used "Start SS3D Host.bat" for the host window and "Start SS3D Client - GhostOfBeep.bat" for the client window. Could it have something to do with GhostOfBeep not being in the permissions file?
