### ISSUE TITLE
Update container system

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#969]
## Summary

The current container system relies mainly on the three following files : 
- Container.cs, supposed to handle the data (what items are in a container ? can it stores an item ? ect ...)
- AttachedContainer.cs, supposed to handle the network logic, and to be a door to container during run time.
- ContainerDescriptor, supposed to orchestrate containers related scripts such as script related to target interactions and such. Give an easy way for users to set up a container with a custom inspector. 

**Supposed** is here because that's not how things are working. Currently, Container is a networkActor, it uses a SyncList to automatically update it's content for observers and one might wonder why we even need AttachedContainer and Container separated then.

The thing is, having everything in one file is tedious : 
- It's too long
- It doesn't allow easy testing since most of the logic is on a monobehaviour.

An older implementation done by @Alainx277 , was an implicit way of following the humble object pattern.
While it was working really well, one issue we could find is that it was customized for containers to update the list of observers, not using the features of our network library of the time which was Mirror. It was quite difficult to read and not applicable to other game systems. 

Now that we moved to Fishnet, is there a way to use Fishnet's features to handle network syncing ? If yes we should go with it and use SyncLists. If no, Alain's way was probably the best next option, and it's time to go full circle. 

## Goal

- Modify Container.cs so it can work independently from AttachedContainer.cs .
- Merge AttachedContainer and ContainerDescriptor into a single script, containerBehaviour.  All functionnalities of Container descriptor must stay, including the custom inspector.
- Remove as much as possible the logic in AttachedContainer.cs and put it in Container.cs
- You can use a Synclist in containerBehaviour, and have a reference to it in container so container can actually update from it, but doesn't have to to work.
- Not all clients should be able to see all containers at all time, look into fishnet's API for a solution : https://firstgeargames.com/FishNet/api/api/FishNet.Observing.ObserverCondition.html

**Comment by stilnat** [comment]
The other solution would be to adopt the humble object design pattern. While this reduce a bit readability, it would allow for easy testing since most of the logic would not be in a behaviour class. We could have a containerBehaviour and a container script. 

We could also merge the content of  ContainerDescriptor and Container, there's no reasons really to separate them now.
That would leave the container system with two main scripts, Container, and ContainerBehaviour.

**Comment by Alainx277** [comment]
Using Synclists is way easier and the way to go. The reason I made a custom solution was that Mirror (and FishNet) don't support "hidden" network variables, so anyone who can see the container object knows what's inside, which makes cheating easier.

If FishNet could support per-variable visibility, that would also help across the whole project.

**Comment by stilnat** [comment]
@Alainx277 I'll have to look more about it but from my understanding, Fishnet doesn't do "network variable hiding" only "network game object hiding". I really don't mind having to use a special game object for the attached container script only, that would show to clients only when we choose to.
