### ISSUE TITLE
Players who checked their readiness did not spawn after the round started

### ISSUE THREAD

**Issue by Notterox** [RE-SS3D/SS3D#973]
## Summary

Starting a round with all players checked their readiness doesn't spawn players.

## Current Behavior

After warmup countdown, nothing happens. In in-game console there is an error:
`Client encountered an error while parsing data for packetId 20. Message: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index.`

## Steps to Reproduce

1. Start host with: "Start SS3D Host.bat" and check "ready"
2. Start client with: "Start SS3D Client - John.bat" and check "ready"
3. As a host, start a round.

## Expected Behavior

After warmup players should spawn normally.

## Possible Solution

It seems that the bug was introduced with 1ee6576948cd08eb6ab48afe2ff1c2ca4cc6a9f9

## Context

Windows 11 (10.0.22621)

**Comment by cosmiccoincidence** [comment]
Fixed in #974
