### ISSUE TITLE
Add automatic client testing 

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#984]
## Summary

Each new PR tend to break previously implemented features. It makes development slow and cumbersome.
As the game complexity is going to increase, it'll be more and more difficult to test edge case situations, such as exotic settings from atmos engineer, station explosions, uncommon entities and event ...

We currently lack the ability to do any sort of automatic testing client side, tocheck if nothing breaks, and to easily test exotic scenarios. 

We don't necessarily want it to be fully automatic, but we want at least reviewers to be able to launch some tests and see if they pass.

here's @Ryan089 suggestion on doing that : 

> **what if we created a command from the client to the server to load a "test mode", then had some API for setup / arrange / teardown stuff on the server from the client. So the reviewer could create a development build to run the server, then run the client tests from within Unity (which orchestrate the actions of the server).**

The idea would be to be able to reproduce these exotic scenarios and tests with minimal efforts, such as clicking on a script, that would set up through commands only player spawning, and creating the conditions for a given scenario.

One component of this process should probably be ` [UnityTest]` : 
https://docs.unity3d.com/Packages/com.unity.test-framework@1.1/manual/reference-attribute-unitytest.html

The kind of test we'd like to do automatically would be : 

- Check if clients can connect correctly when the server launch the round.
- Check if client UI is working as expected, such as dropping item sprite on it should show the sprite in the UI slots.
- Check if client can receive damage as expected in multiple scenarios.
-  Check if an item enters the inventory once the player has picked it up.
- ...

Maybe [that video](https://www.youtube.com/watch?v=X673tOi8pU8) about doing something similar on UE can help or provide some inspirations .

**Comment by Ryan089** [comment]
I will attempt this one.

**Comment by Ryan089** [comment]
I have been unable to achieve meaningful progress in the last fortnight. Releasing the task now for someone else to attempt the bounty if desired.
