### ISSUE TITLE
Propagating Pocket Problem

### ISSUE THREAD

**Issue by Ryan089** [RE-SS3D/SS3D#990]
## Summary

Pockets can duplicate between rounds. Needless to say, this should not occur.

## Current Behavior

Ending a round, then starting a new round will cause additional pockets to appear in the player UI.

## Steps to Reproduce

1. Launch game
2. Set player to "Ready"
3. Start round.
4. Observe number of pocket slots.
5. Stop round.
6. Set player to "Ready"
7. Start round
8. Observe that the number of pocket slots has increased.
9. Repeat steps 5-8 as many times as desired.

## Pictures

![More Pockets](https://user-images.githubusercontent.com/64360820/215306900-96c9e615-5615-4f1a-95b9-26b062553a11.PNG)
**Hierarchy view**

![Too many pockets](https://user-images.githubusercontent.com/64360820/215306904-8356db10-e7b3-492f-98fa-35a77aac9043.PNG)
**Interface**

## Expected Behavior

Pockets shouldn't breed between rounds.

## Possible Solution

Pockets were implemented in #977, so start looking from there.

## Context

Applicable both using a host, as well as client and dedicated server.

**Comment by cosmiccoincidence** [comment]
@stilnat You have worked with the inventory recently, is this still a problem?

**Comment by stilnat** [comment]
@cosmiccoincidence We have other issues with inventory slots but not this one I believe.
