### ISSUE TITLE
Lobby: Player list does not update when players have left

### ISSUE THREAD

**Issue by Ryan089** [RE-SS3D/SS3D#994]
## Summary

The Lobby screen lists when players have joined the server. However, it does not remove them from that list when they leave.

## Current Behavior

Once you have entered the Lobby, your ckey will be listed on the player list of all players even after you have shut down the game.

## Steps to Reproduce

1. Create a compiled build of the game using **File > Build Settings > Build**.

2. Run a host using either of the methods described [here](https://ss3d.gitbook.io/programming/guides/running/hosting-a-server). *(In theory you could use a dedicated server instead; however, the player list is broken on that in a different way, see #993)*

3. Join the server as described [here](https://ss3d.gitbook.io/programming/guides/running/joining-a-server) using both GhostOfBeep and John .bat files.

4. Observe that everyone can see each other in the player list.

5. Exit the application for the "GhostOfBeep" instance.

6. Observe that "HostingUser" and "John" still have "GhostOfBeep" on their player list.

## Expected Behavior

When a player leaves, their name should be removed from the list.

**Comment by stilnat** [comment]
@Ryan089 Is "leaving" simply closing the window or another thing ?

**Comment by Ryan089** [comment]
That's correct - simply closing the window. I don't think we have a 'proper' way to leave yet.
